// frontend/src/routes/quiz/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { getAuth } from '$lib/auth.svelte';
  import { goto } from '$app/navigation';
  import { api } from '$lib/api';
  import QuestionCard from '$lib/components/QuestionCard.svelte';
  import CategoryFilter from '$lib/components/CategoryFilter.svelte';
  import SessionSummary from '$lib/components/SessionSummary.svelte';

  const auth = getAuth();

  $effect(() => {
    if (!auth.loading && !auth.user) goto('/login');
  });

  // --- State ---
  let question = $state<any>(null);
  let prefetchedQuestion = $state<any>(null);
  let showAnswer = $state(false);
  let loading = $state(true);
  let error = $state('');
  let sessionId = $state<number | null>(null);
  let categories = $state<Array<{ name: string; count: number }>>([]);
  let selectedCategory = $state('all');
  let runningStats = $state({ total: 0, correct: 0 });
  let gameTypeFilters = $state<string[]>([]);
  let showSessionSummary = $state(false);
  let sessionSummary = $state<any>(null);
  let submitting = $state(false);
  let showEndConfirm = $state(false);

  // Derived accuracy
  let accuracy = $derived(
    runningStats.total > 0
      ? Math.round((runningStats.correct / runningStats.total) * 100)
      : 0
  );

  // --- API helpers ---
  function buildQuizParams(): URLSearchParams {
    const params = new URLSearchParams();
    if (selectedCategory !== 'all') params.set('category', selectedCategory);
    if (gameTypeFilters.length > 0) params.set('gameTypes', gameTypeFilters.join(','));
    return params;
  }

  async function fetchQuestion() {
    loading = true;
    error = '';
    try {
      const params = buildQuizParams();
      const q = await api.get(`/api/quiz/random?${params}`);
      question = q;
    } catch (err: any) {
      error = err?.message ?? 'Failed to load question';
    } finally {
      loading = false;
    }
  }

  function prefetchNextQuestion() {
    const params = buildQuizParams();
    fetch(`/api/quiz/random?${params}`, { credentials: 'same-origin' })
      .then((r) => r.json())
      .then((q) => {
        prefetchedQuestion = q;
      })
      .catch(() => {});
  }

  async function handleAnswer(correct: boolean) {
    if (submitting) return;
    submitting = true;
    try {
      const result = await api.post('/api/quiz/submit', {
        questionId: question.id,
        correct,
        sessionId,
        isReviewSession: false,
      });
      sessionId = result.sessionId;
      runningStats.total++;
      if (correct) runningStats.correct++;

      if (prefetchedQuestion) {
        question = prefetchedQuestion;
        prefetchedQuestion = null;
      } else {
        await fetchQuestion();
      }
      showAnswer = false;
    } catch (err: any) {
      error = err?.message ?? 'Failed to submit answer';
    } finally {
      submitting = false;
    }
  }

  async function handleArchive() {
    if (!question) return;
    try {
      await api.post(`/api/questions/${question.id}/archive`, {
        reason: 'Missing media or problematic question',
      });
      // Move to next question
      if (prefetchedQuestion) {
        question = prefetchedQuestion;
        prefetchedQuestion = null;
      } else {
        await fetchQuestion();
      }
      showAnswer = false;
    } catch (err: any) {
      error = err?.message ?? 'Failed to archive question';
    }
  }

  async function handleEndSession() {
    if (!sessionId) {
      showEndConfirm = false;
      return;
    }
    try {
      const result = await api.post('/api/quiz/complete', { sessionId });
      sessionSummary = result.summary;
      showSessionSummary = true;
    } catch (err: any) {
      error = err?.message ?? 'Failed to end session';
    } finally {
      showEndConfirm = false;
    }
  }

  async function savePreferences() {
    try {
      await api.put('/api/preferences', { gameTypeFilters });
    } catch {
      // Non-critical
    }
  }

  async function handleCategoryChange(value: string) {
    selectedCategory = value;
    prefetchedQuestion = null;
    await fetchQuestion();
  }

  function toggleGameTypeFilter(type: string) {
    if (gameTypeFilters.includes(type)) {
      gameTypeFilters = gameTypeFilters.filter((t) => t !== type);
    } else {
      gameTypeFilters = [...gameTypeFilters, type];
    }
    savePreferences();
    prefetchedQuestion = null;
    fetchQuestion();
  }

  // --- Keyboard shortcuts ---
  function handleKeydown(e: KeyboardEvent) {
    if (e.target instanceof HTMLInputElement || e.target instanceof HTMLSelectElement) return;

    if (e.code === 'Space' && !showAnswer) {
      e.preventDefault();
      showAnswer = true;
      prefetchNextQuestion();
    } else if (e.code === 'ArrowRight' && showAnswer && !submitting) {
      handleAnswer(true);
    } else if (e.code === 'ArrowLeft' && showAnswer && !submitting) {
      handleAnswer(false);
    }
  }

  // --- Mount ---
  onMount(async () => {
    try {
      const [cats, prefs] = await Promise.all([
        api.get('/api/categories'),
        api.get('/api/preferences'),
      ]);
      categories = cats ?? [];
      gameTypeFilters = prefs?.gameTypeFilters ?? [];
    } catch {
      // Non-critical; continue
    }
    await fetchQuestion();
  });
</script>

<svelte:window onkeydown={handleKeydown} />

<div class="min-h-screen bg-gray-50 py-6 px-4">
  <div class="max-w-2xl mx-auto flex flex-col gap-4">

    <!-- Header row -->
    <div class="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3">
      <h1 class="text-2xl font-bold text-jeopardy-blue">Quiz</h1>

      <!-- Running stats -->
      {#if runningStats.total > 0}
        <div class="text-sm font-medium text-gray-600">
          <span class="text-green-600 font-bold">{runningStats.correct}</span>
          / {runningStats.total} correct
          (<span class="{accuracy >= 75 ? 'text-green-600' : accuracy >= 50 ? 'text-amber-500' : 'text-red-500'} font-bold">{accuracy}%</span>)
        </div>
      {/if}

      <!-- End session button -->
      {#if sessionId}
        <button
          onclick={() => (showEndConfirm = true)}
          class="px-4 py-1.5 rounded-lg border border-gray-300 text-sm text-gray-700 hover:bg-gray-100 transition-colors"
        >
          End Session
        </button>
      {/if}
    </div>

    <!-- Filters -->
    <div class="bg-white rounded-xl shadow-sm px-5 py-4 flex flex-col sm:flex-row sm:items-center gap-4">
      <div class="flex-1">
        <p class="block text-xs font-semibold text-gray-500 uppercase tracking-wide mb-1">Category</p>
        <CategoryFilter
          {categories}
          selected={selectedCategory}
          onchange={handleCategoryChange}
        />
      </div>

      <div>
        <p class="text-xs font-semibold text-gray-500 uppercase tracking-wide mb-2">Exclude Game Types</p>
        <div class="flex flex-wrap gap-3">
          {#each ['Kids', 'Teen', 'College'] as type}
            <label class="flex items-center gap-1.5 text-sm text-gray-700 cursor-pointer">
              <input
                type="checkbox"
                checked={gameTypeFilters.includes(type)}
                onchange={() => toggleGameTypeFilter(type)}
                class="w-4 h-4 rounded border-gray-300 text-jeopardy-blue focus:ring-jeopardy-blue"
              />
              {type}
            </label>
          {/each}
        </div>
      </div>
    </div>

    <!-- Error banner -->
    {#if error}
      <div class="px-4 py-3 bg-red-50 border border-red-200 text-red-700 rounded-lg text-sm">
        {error}
        <button onclick={() => (error = '')} class="ml-2 underline text-red-500">Dismiss</button>
      </div>
    {/if}

    <!-- Question card -->
    {#if loading && !question}
      <div class="flex justify-center py-20">
        <div class="animate-spin rounded-full h-12 w-12 border-b-2 border-jeopardy-blue"></div>
      </div>
    {:else if question}
      <div class="min-h-[420px]">
        <QuestionCard
          clue={question.answer}
          answer={question.question}
          category={question.category}
          classifierCategory={question.classifier_category ?? question.classifierCategory ?? question.category}
          clueValue={question.clue_value ?? question.clueValue ?? null}
          round={question.round ?? null}
          airDate={question.air_date ?? question.airDate ?? null}
          {showAnswer}
          onRevealAnswer={() => {
            showAnswer = true;
            prefetchNextQuestion();
          }}
          onCorrect={() => handleAnswer(true)}
          onIncorrect={() => handleAnswer(false)}
          {submitting}
        >
          {#snippet additionalActions()}
            {#if showAnswer}
              <button
                onclick={handleArchive}
                class="w-full py-2 rounded-lg bg-white/10 hover:bg-white/20 border border-white/20 text-white/80 text-sm font-medium transition-colors"
              >
                Archive (problematic question)
              </button>
            {/if}
          {/snippet}
        </QuestionCard>
      </div>

      <!-- Keyboard hint -->
      <p class="text-center text-xs text-gray-400">
        {#if !showAnswer}
          Press <kbd class="px-1.5 py-0.5 bg-gray-100 rounded border border-gray-300 font-mono">Space</kbd> to reveal answer
        {:else}
          <kbd class="px-1.5 py-0.5 bg-gray-100 rounded border border-gray-300 font-mono">←</kbd> Incorrect &nbsp;
          <kbd class="px-1.5 py-0.5 bg-gray-100 rounded border border-gray-300 font-mono">→</kbd> Correct
        {/if}
      </p>
    {:else}
      <div class="text-center py-16 text-gray-500">No questions available for the selected filters.</div>
    {/if}

  </div>
</div>

<!-- End session confirmation -->
{#if showEndConfirm}
  <div class="fixed inset-0 z-50 flex items-center justify-center bg-black/60 px-4">
    <div class="w-full max-w-sm rounded-2xl bg-white shadow-2xl p-6 flex flex-col gap-4">
      <h2 class="text-lg font-bold text-gray-800">End Session?</h2>
      <p class="text-sm text-gray-600">This will complete your current quiz session and show a summary.</p>
      <div class="flex gap-3">
        <button
          onclick={() => (showEndConfirm = false)}
          class="flex-1 py-2.5 rounded-xl border border-gray-300 text-gray-700 text-sm font-medium hover:bg-gray-50 transition-colors"
        >
          Cancel
        </button>
        <button
          onclick={handleEndSession}
          class="flex-1 py-2.5 rounded-xl bg-jeopardy-blue text-white text-sm font-semibold hover:bg-blue-800 transition-colors"
        >
          End Session
        </button>
      </div>
    </div>
  </div>
{/if}

<!-- Session summary modal -->
{#if showSessionSummary && sessionSummary}
  <SessionSummary
    summary={sessionSummary}
    onclose={() => {
      showSessionSummary = false;
      sessionId = null;
      runningStats = { total: 0, correct: 0 };
      goto('/dashboard');
    }}
  />
{/if}

// app/quiz/page.tsx
"use client";

import { useState, useEffect } from "react";
import { useSession } from "next-auth/react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import Navigation from "../components/Navigation";
import QuestionCard from "../components/QuestionCard";

interface Question {
  id: number;
  question: string;
  answer: string;
  category: string;
  classifier_category: string;
  clue_value: number | null;
  round: number | null;
  air_date: string | null;
  notes: string | null;
}

export default function QuizPage() {
  const { data: session, status } = useSession();
  const router = useRouter();
  const [question, setQuestion] = useState<Question | null>(null);
  const [prefetchedQuestion, setPrefetchedQuestion] = useState<Question | null>(null);
  const [showAnswer, setShowAnswer] = useState(false);
  const [loading, setLoading] = useState(true);
  const [sessionId, setSessionId] = useState<number | null>(null);
  const [categories, setCategories] = useState<Array<{ name: string; count: number }>>([]);
  const [selectedCategory, setSelectedCategory] = useState("all");
  const [stats, setStats] = useState({ total: 0, correct: 0 });
  const [gameTypeFilters, setGameTypeFilters] = useState<string[]>([]);
  const [loadingPreferences, setLoadingPreferences] = useState(true);
  const [showSessionSummary, setShowSessionSummary] = useState(false);
  const [sessionSummary, setSessionSummary] = useState<any>(null);

  useEffect(() => {
    if (status === "unauthenticated") {
      router.push("/login");
    }
  }, [status, router]);

  useEffect(() => {
    fetchCategories();
  }, []);

  useEffect(() => {
    if (status === "authenticated") {
      loadPreferences();
    }
  }, [status]);

  useEffect(() => {
    if (status === "authenticated" && !loadingPreferences) {
      fetchQuestion();
    }
  }, [status, selectedCategory, gameTypeFilters, loadingPreferences]);

  // Prefetch next question when answer is revealed
  useEffect(() => {
    if (showAnswer && !prefetchedQuestion) {
      prefetchNextQuestion();
    }
  }, [showAnswer]);

  // Keyboard shortcuts
  useEffect(() => {
    const handleKeyPress = (e: KeyboardEvent) => {
      // Ignore if typing in an input
      if (e.target instanceof HTMLInputElement || e.target instanceof HTMLSelectElement) {
        return;
      }

      if (e.key === " " || e.key === "Spacebar") {
        e.preventDefault();
        if (!showAnswer) {
          setShowAnswer(true);
        }
      } else if (e.key === "ArrowLeft" && showAnswer) {
        e.preventDefault();
        handleAnswer(false);
      } else if (e.key === "ArrowRight" && showAnswer) {
        e.preventDefault();
        handleAnswer(true);
      }
    };

    window.addEventListener("keydown", handleKeyPress);
    return () => window.removeEventListener("keydown", handleKeyPress);
  }, [showAnswer, question]);

  const fetchCategories = async () => {
    try {
      const response = await fetch("/api/categories");
      const data = await response.json();
      setCategories(data);
    } catch (error) {
      console.error("Error fetching categories:", error);
    }
  };

  const loadPreferences = async () => {
    try {
      const response = await fetch("/api/preferences");
      const data = await response.json();
      if (data.gameTypeFilters) {
        setGameTypeFilters(data.gameTypeFilters);
      }
    } catch (error) {
      console.error("Error loading preferences:", error);
    } finally {
      setLoadingPreferences(false);
    }
  };

  const savePreferences = async (filters: string[]) => {
    try {
      await fetch("/api/preferences", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ gameTypeFilters: filters }),
      });
    } catch (error) {
      console.error("Error saving preferences:", error);
    }
  };

  const buildQuizUrl = () => {
    const params = new URLSearchParams();
    if (selectedCategory !== "all") {
      params.append("category", selectedCategory);
    }
    if (gameTypeFilters.length > 0) {
      params.append("gameTypes", gameTypeFilters.join(","));
    }
    return `/api/quiz/random${params.toString() ? `?${params.toString()}` : ""}`;
  };

  const fetchQuestion = async (usePrefetch = true) => {
    // If we have a prefetched question and it's for the same category, use it
    if (usePrefetch && prefetchedQuestion && selectedCategory === selectedCategory) {
      setQuestion(prefetchedQuestion);
      setPrefetchedQuestion(null);
      setShowAnswer(false);
      setLoading(false);
      // Prefetch the next one in the background
      prefetchNextQuestion();
      return;
    }

    setLoading(true);
    setShowAnswer(false);

    try {
      const url = buildQuizUrl();
      const response = await fetch(url);
      const data = await response.json();
      setQuestion(data);
      setLoading(false);
      // Prefetch the next one in the background
      prefetchNextQuestion();
    } catch (error) {
      console.error("Error fetching question:", error);
      setLoading(false);
    }
  };

  const prefetchNextQuestion = async () => {
    try {
      const url = buildQuizUrl();
      const response = await fetch(url);
      const data = await response.json();
      setPrefetchedQuestion(data);
    } catch (error) {
      console.error("Error prefetching question:", error);
    }
  };

  const handleAnswer = async (correct: boolean) => {
    if (!question) return;

    // Update stats immediately for responsive UI
    setStats((prev) => ({
      total: prev.total + 1,
      correct: prev.correct + (correct ? 1 : 0),
    }));

    // If we have a prefetched question, show it immediately and submit in background
    if (prefetchedQuestion) {
      setQuestion(prefetchedQuestion);
      setPrefetchedQuestion(null);
      setShowAnswer(false);

      // Submit answer and prefetch next question in parallel
      Promise.all([
        fetch("/api/quiz/submit", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ questionId: question.id, correct, sessionId }),
        }).then(async (response) => {
          const data = await response.json();
          if (data.sessionId && !sessionId) {
            setSessionId(data.sessionId);
          }
        }),
        prefetchNextQuestion(),
      ]).catch((error) => {
        console.error("Error in background operations:", error);
      });
    } else {
      // No prefetched question - run submit and fetch in parallel
      try {
        const [submitResponse] = await Promise.all([
          fetch("/api/quiz/submit", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({ questionId: question.id, correct, sessionId }),
          }),
          fetchQuestion(false), // Don't try to use prefetch since we know it's null
        ]);

        const data = await submitResponse.json();
        if (data.sessionId && !sessionId) {
          setSessionId(data.sessionId);
        }
      } catch (error) {
        console.error("Error submitting answer:", error);
      }
    }
  };

  const handleArchive = async () => {
    if (!question) return;

    if (!confirm("Archive this question? This will hide it for all users (useful for questions with missing media).")) {
      return;
    }

    try {
      // Archive and fetch next question in parallel
      await Promise.all([
        fetch("/api/archive", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            questionId: question.id,
            reason: "Missing media or unanswerable",
          }),
        }),
        fetchQuestion(true), // Use prefetch if available
      ]);
    } catch (error) {
      console.error("Error archiving question:", error);
    }
  };

  const handleEndSession = async () => {
    if (!sessionId) {
      alert("No active session to end");
      return;
    }

    if (!confirm("End this quiz session?")) {
      return;
    }

    try {
      const response = await fetch("/api/quiz/complete", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ sessionId }),
      });

      const data = await response.json();

      if (data.success) {
        setSessionSummary(data.summary);
        setShowSessionSummary(true);
        setSessionId(null);
        setStats({ total: 0, correct: 0 });
      } else {
        alert(data.error || "Failed to end session");
      }
    } catch (error) {
      console.error("Error ending session:", error);
      alert("Failed to end session");
    }
  };

  const handleGameTypeFilterChange = (type: string, checked: boolean) => {
    const newFilters = checked
      ? [...gameTypeFilters, type]
      : gameTypeFilters.filter((f) => f !== type);

    setGameTypeFilters(newFilters);
    savePreferences(newFilters);
  };

  if (status === "loading" || loading) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-gray-100">
        <div className="text-xl">Loading...</div>
      </div>
    );
  }

  if (!question) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-gray-100">
        <div className="text-xl">No questions found</div>
      </div>
    );
  }

  const accuracy = stats.total > 0 ? Math.round((stats.correct / stats.total) * 100) : 0;

  return (
    <div className="min-h-screen bg-gray-100">
      <Navigation title="Jeopardy! Training" username={session?.user?.username} userRole={session?.user?.role} />

      {/* Session Stats & Category Filter */}
      <div className="bg-white shadow-sm p-3 sm:p-4">
        <div className="max-w-6xl mx-auto">
          <div className="mb-3 sm:mb-4 flex flex-col sm:flex-row items-center justify-between gap-2">
            <div className="flex-1"></div>
            <span className="text-xs sm:text-sm font-medium text-gray-700">
              Session: {stats.correct}/{stats.total} ({accuracy}%)
            </span>
            <div className="flex-1 flex justify-end">
              {sessionId && stats.total > 0 && (
                <button
                  onClick={handleEndSession}
                  className="px-3 py-1 text-xs sm:text-sm bg-gray-600 text-white rounded hover:bg-gray-700 transition-colors"
                >
                  End Session
                </button>
              )}
            </div>
          </div>

          {/* Category Filter */}
          <div className="mb-3 sm:mb-4">
            <label className="block text-xs sm:text-sm font-medium text-gray-700 mb-2">
              Category Filter:
            </label>
            <select
              value={selectedCategory}
              onChange={(e) => setSelectedCategory(e.target.value)}
              className="w-full sm:w-auto px-3 sm:px-4 py-2 text-sm sm:text-base border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-jeopardy-blue"
            >
              <option value="all">All Categories</option>
              {categories.map((cat) => (
                <option key={cat.name} value={cat.name}>
                  {cat.name} ({cat.count})
                </option>
              ))}
            </select>
          </div>

          {/* Game Type Filter */}
          <div className="border-t border-gray-200 pt-3 sm:pt-4">
            <label className="block text-xs sm:text-sm font-medium text-gray-700 mb-2">
              Difficulty Level (Youth Mode):
            </label>
            <div className="flex flex-wrap gap-3 sm:gap-4">
              <label className="flex items-center gap-2 cursor-pointer">
                <input
                  type="checkbox"
                  checked={gameTypeFilters.includes("kids")}
                  onChange={(e) => handleGameTypeFilterChange("kids", e.target.checked)}
                  className="w-4 h-4 text-jeopardy-blue border-gray-300 rounded focus:ring-jeopardy-blue"
                />
                <span className="text-xs sm:text-sm text-gray-700">Kids Jeopardy</span>
              </label>
              <label className="flex items-center gap-2 cursor-pointer">
                <input
                  type="checkbox"
                  checked={gameTypeFilters.includes("teen")}
                  onChange={(e) => handleGameTypeFilterChange("teen", e.target.checked)}
                  className="w-4 h-4 text-jeopardy-blue border-gray-300 rounded focus:ring-jeopardy-blue"
                />
                <span className="text-xs sm:text-sm text-gray-700">Teen Jeopardy</span>
              </label>
              <label className="flex items-center gap-2 cursor-pointer">
                <input
                  type="checkbox"
                  checked={gameTypeFilters.includes("college")}
                  onChange={(e) => handleGameTypeFilterChange("college", e.target.checked)}
                  className="w-4 h-4 text-jeopardy-blue border-gray-300 rounded focus:ring-jeopardy-blue"
                />
                <span className="text-xs sm:text-sm text-gray-700">College Championship</span>
              </label>
              {gameTypeFilters.length > 0 && (
                <button
                  onClick={() => {
                    setGameTypeFilters([]);
                    savePreferences([]);
                  }}
                  className="text-xs text-gray-500 hover:text-gray-700 underline"
                >
                  Clear Filters
                </button>
              )}
            </div>
            {gameTypeFilters.length > 0 && (
              <p className="text-xs text-gray-500 mt-2 italic">
                Filter saved - will persist across sessions
              </p>
            )}
          </div>
        </div>
      </div>

      {/* Question Card */}
      <div className="max-w-4xl mx-auto p-3 sm:p-4 md:p-6 lg:p-8">
        <QuestionCard
          clue={question.answer}
          answer={question.question}
          category={question.category}
          classifierCategory={question.classifier_category}
          clueValue={question.clue_value}
          round={question.round}
          airDate={question.air_date}
          showAnswer={showAnswer}
          onRevealAnswer={() => setShowAnswer(true)}
          onCorrect={() => handleAnswer(true)}
          onIncorrect={() => handleAnswer(false)}
          keyboardHint={
            showAnswer
              ? "Press ← for Incorrect | → for Correct"
              : "Press Space to reveal"
          }
          archiveButton={
            showAnswer ? (
              <button
                onClick={handleArchive}
                className="px-3 py-1 text-xs text-gray-300 hover:text-white underline transition-colors"
              >
                Archive question (if media missing)
              </button>
            ) : undefined
          }
        />
      </div>

      {/* Session Summary Modal */}
      {showSessionSummary && sessionSummary && (
        <div className="fixed inset-0 bg-black bg-opacity-75 flex items-center justify-center z-50 p-4">
          <div className="bg-white rounded-lg max-w-md w-full p-6 sm:p-8">
            <h2 className="text-2xl font-bold text-jeopardy-blue mb-6 text-center">
              Session Complete!
            </h2>

            <div className="space-y-4 mb-6">
              <div className="bg-gray-50 p-4 rounded-lg">
                <div className="text-center">
                  <div className="text-4xl font-bold text-jeopardy-blue mb-2">
                    {sessionSummary.accuracy}%
                  </div>
                  <div className="text-sm text-gray-600">Accuracy</div>
                </div>
              </div>

              <div className="grid grid-cols-3 gap-3 text-center">
                <div className="bg-gray-50 p-3 rounded">
                  <div className="text-2xl font-bold text-gray-700">
                    {sessionSummary.total}
                  </div>
                  <div className="text-xs text-gray-500">Total</div>
                </div>
                <div className="bg-green-50 p-3 rounded">
                  <div className="text-2xl font-bold text-green-600">
                    {sessionSummary.correct}
                  </div>
                  <div className="text-xs text-gray-500">Correct</div>
                </div>
                <div className="bg-red-50 p-3 rounded">
                  <div className="text-2xl font-bold text-red-600">
                    {sessionSummary.incorrect}
                  </div>
                  <div className="text-xs text-gray-500">Incorrect</div>
                </div>
              </div>

              <div className="text-center text-sm text-gray-600">
                <div>
                  Started: {new Date(sessionSummary.started_at).toLocaleTimeString()}
                </div>
                <div>
                  Ended: {new Date(sessionSummary.completed_at).toLocaleTimeString()}
                </div>
              </div>
            </div>

            <div className="flex gap-3">
              <button
                onClick={() => {
                  setShowSessionSummary(false);
                  router.push("/dashboard");
                }}
                className="flex-1 px-4 py-2 bg-gray-600 text-white font-semibold rounded-lg hover:bg-gray-700 transition-colors"
              >
                Go to Dashboard
              </button>
              <button
                onClick={() => setShowSessionSummary(false)}
                className="flex-1 px-4 py-2 bg-jeopardy-blue text-white font-semibold rounded-lg hover:bg-blue-700 transition-colors"
              >
                Start New Session
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
