// app/review/page.tsx
"use client";

import { useState, useEffect } from "react";
import { useSession } from "next-auth/react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import Navigation from "../components/Navigation";
import QuestionCard from "../components/QuestionCard";

interface WrongAnswer {
  question: {
    id: number;
    question: string;
    answer: string;
    category: string;
    classifier_category: string;
    clue_value: number | null;
    round: number | null;
    air_date: string | null;
  };
  masteryProgress: {
    consecutive_correct: number;
    required: number;
  };
}

export default function ReviewPage() {
  const { data: session, status } = useSession();
  const router = useRouter();
  const [wrongAnswers, setWrongAnswers] = useState<WrongAnswer[]>([]);
  const [loading, setLoading] = useState(true);
  const [categories, setCategories] = useState<Array<{ name: string; count: number }>>([]);
  const [selectedCategory, setSelectedCategory] = useState("all");
  const [expandedId, setExpandedId] = useState<number | null>(null);

  // Review session state
  const [inSession, setInSession] = useState(false);
  const [sessionQuestions, setSessionQuestions] = useState<WrongAnswer[]>([]);
  const [currentIndex, setCurrentIndex] = useState(0);
  const [revealed, setRevealed] = useState(false);
  const [submitting, setSubmitting] = useState(false);

  useEffect(() => {
    if (status === "unauthenticated") {
      router.push("/login");
    }
  }, [status, router]);

  useEffect(() => {
    if (status === "authenticated") {
      fetchCategories();
      fetchWrongAnswers();
    }
  }, [status, selectedCategory]);

  const fetchCategories = async () => {
    try {
      const response = await fetch("/api/categories");
      const data = await response.json();
      setCategories(data);
    } catch (error) {
      console.error("Error fetching categories:", error);
    }
  };

  const fetchWrongAnswers = async () => {
    setLoading(true);

    try {
      const url = selectedCategory === "all"
        ? "/api/review"
        : `/api/review?category=${encodeURIComponent(selectedCategory)}`;

      const response = await fetch(url);
      const data = await response.json();
      setWrongAnswers(data);
    } catch (error) {
      console.error("Error fetching wrong answers:", error);
    } finally {
      setLoading(false);
    }
  };

  const handleArchive = async (questionId: number) => {
    if (!confirm("Archive this question? This will hide it for all users (useful for questions with missing media).")) {
      return;
    }

    try {
      await fetch("/api/archive", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          questionId,
          reason: "Missing media or unanswerable",
        }),
      });

      // Refresh the list
      fetchWrongAnswers();
    } catch (error) {
      console.error("Error archiving question:", error);
    }
  };

  const startReviewSession = () => {
    setSessionQuestions([...wrongAnswers]);
    setCurrentIndex(0);
    setRevealed(false);
    setInSession(true);
  };

  const endReviewSession = () => {
    setInSession(false);
    setSessionQuestions([]);
    setCurrentIndex(0);
    setRevealed(false);
    fetchWrongAnswers(); // Refresh to show updated progress
  };

  const handleSessionSubmit = async (correct: boolean) => {
    if (submitting) return;

    setSubmitting(true);

    try {
      await fetch("/api/quiz/submit", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          questionId: sessionQuestions[currentIndex].question.id,
          correct,
          isReviewSession: true,
        }),
      });

      // Move to next question or end session
      if (currentIndex + 1 < sessionQuestions.length) {
        setCurrentIndex(currentIndex + 1);
        setRevealed(false);
      } else {
        // Session complete
        alert("Review session complete!");
        endReviewSession();
      }
    } catch (error) {
      console.error("Error submitting answer:", error);
      alert("Error submitting answer");
    } finally {
      setSubmitting(false);
    }
  };

  if (status === "loading" || loading) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-gray-100">
        <div className="text-xl">Loading...</div>
      </div>
    );
  }

  // Review Session UI
  if (inSession && sessionQuestions.length > 0) {
    const currentQuestion = sessionQuestions[currentIndex].question;

    return (
      <div className="min-h-screen bg-gray-100">
        {/* Header */}
        <div className="bg-jeopardy-blue text-white p-3 sm:p-4">
          <div className="max-w-4xl mx-auto flex justify-between items-center gap-2">
            <h1 className="text-lg sm:text-xl md:text-2xl font-bold">Review Session</h1>
            <button
              onClick={endReviewSession}
              className="px-3 py-1.5 sm:px-4 sm:py-2 text-sm sm:text-base bg-white text-jeopardy-blue rounded hover:bg-gray-100 transition-colors whitespace-nowrap"
            >
              End Session
            </button>
          </div>
        </div>

        {/* Progress */}
        <div className="bg-white shadow-sm p-3 sm:p-4">
          <div className="max-w-4xl mx-auto">
            <div className="flex justify-between text-xs sm:text-sm text-gray-600">
              <span>Question {currentIndex + 1} of {sessionQuestions.length}</span>
              <span>{Math.round(((currentIndex) / sessionQuestions.length) * 100)}% Complete</span>
            </div>
            <div className="mt-2 w-full bg-gray-200 rounded-full h-2">
              <div
                className="bg-jeopardy-blue h-2 rounded-full transition-all"
                style={{ width: `${(currentIndex / sessionQuestions.length) * 100}%` }}
              ></div>
            </div>
          </div>
        </div>

        {/* Question Card */}
        <div className="max-w-4xl mx-auto p-3 sm:p-4 md:p-6 lg:p-8">
          <QuestionCard
            clue={currentQuestion.answer}
            answer={currentQuestion.question}
            category={currentQuestion.category}
            classifierCategory={currentQuestion.classifier_category}
            clueValue={currentQuestion.clue_value}
            airDate={currentQuestion.air_date}
            showAnswer={revealed}
            onRevealAnswer={() => setRevealed(true)}
            onCorrect={() => handleSessionSubmit(true)}
            onIncorrect={() => handleSessionSubmit(false)}
            submitting={submitting}
          />
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-100">
      <Navigation title="Review Wrong Answers" username={session?.user?.username} userRole={session?.user?.role} />

      {/* Category Filter */}
      <div className="bg-white shadow-sm p-3 sm:p-4">
        <div className="max-w-6xl mx-auto">
          <label className="block text-xs sm:text-sm font-medium text-gray-700 mb-2">
            Filter by Category:
          </label>
          <select
            value={selectedCategory}
            onChange={(e) => setSelectedCategory(e.target.value)}
            className="w-full sm:w-auto px-3 sm:px-4 py-2 text-sm sm:text-base border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-jeopardy-blue"
          >
            <option value="all">All Categories</option>
            {categories.map((cat) => (
              <option key={cat.name} value={cat.name}>
                {cat.name}
              </option>
            ))}
          </select>
        </div>
      </div>

      <div className="max-w-6xl mx-auto p-3 sm:p-4 md:p-6 lg:p-8">
        {wrongAnswers.length === 0 ? (
          <div className="bg-white p-6 sm:p-8 md:p-12 rounded-lg shadow text-center">
            <h2 className="text-xl sm:text-2xl font-bold text-gray-800 mb-4">
              No Wrong Answers Found!
            </h2>
            <p className="text-sm sm:text-base text-gray-600 mb-6">
              {selectedCategory === "all"
                ? "You haven't answered any questions incorrectly yet, or you haven't started quizzing."
                : `You haven't answered any questions incorrectly in the ${selectedCategory} category.`}
            </p>
            <Link
              href="/quiz"
              className="inline-block px-6 py-2 sm:px-8 sm:py-3 text-sm sm:text-base bg-jeopardy-blue text-white font-bold rounded-lg hover:bg-blue-700 transition-colors"
            >
              Start Quiz
            </Link>
          </div>
        ) : (
          <>
            <div className="mb-4 sm:mb-6 flex flex-col sm:flex-row justify-between items-start sm:items-center gap-3 sm:gap-4">
              <h2 className="text-base sm:text-lg md:text-xl font-semibold text-gray-800">
                Found {wrongAnswers.length} question{wrongAnswers.length !== 1 ? "s" : ""} to review
              </h2>
              <button
                onClick={startReviewSession}
                className="w-full sm:w-auto px-4 sm:px-6 py-2 sm:py-3 text-sm sm:text-base bg-jeopardy-blue text-white font-bold rounded-lg hover:bg-blue-700 transition-colors whitespace-nowrap"
              >
                Start Review Session
              </button>
            </div>

            <div className="space-y-4">
              {wrongAnswers.map((item) => {
                const progress = item.masteryProgress.consecutive_correct;
                const required = item.masteryProgress.required;

                // Determine badge color based on progress
                let badgeColor = "bg-red-100 text-red-800"; // 0/3
                if (progress === 1) badgeColor = "bg-yellow-100 text-yellow-800"; // 1/3
                if (progress === 2) badgeColor = "bg-orange-100 text-orange-800"; // 2/3

                return (
                  <div
                    key={item.question.id}
                    className="bg-white rounded-lg shadow hover:shadow-md transition-shadow"
                  >
                    <div
                      className="p-4 sm:p-6 cursor-pointer"
                      onClick={() =>
                        setExpandedId(expandedId === item.question.id ? null : item.question.id)
                      }
                    >
                      <div className="flex justify-between items-start gap-2">
                        <div className="flex-1 min-w-0">
                          <div className="flex flex-wrap items-center gap-2 sm:gap-3 mb-2">
                            <span className="px-2 sm:px-3 py-1 bg-blue-100 text-blue-800 text-xs font-semibold rounded-full">
                              {item.question.classifier_category}
                            </span>
                            {item.question.clue_value && (
                              <span className="text-xs sm:text-sm text-gray-500">
                                ${item.question.clue_value}
                              </span>
                            )}
                            <span className={`px-2 sm:px-3 py-1 ${badgeColor} text-xs font-semibold rounded-full whitespace-nowrap`}>
                              Progress: {progress}/{required} ✓
                            </span>
                          </div>
                          <p className="text-sm sm:text-base md:text-lg font-medium text-gray-900 break-words">
                            {item.question.answer}
                          </p>
                        </div>
                        <button className="text-gray-400 hover:text-gray-600 text-xl flex-shrink-0 ml-2">
                          {expandedId === item.question.id ? "−" : "+"}
                        </button>
                      </div>

                      {expandedId === item.question.id && (
                      <div className="mt-3 sm:mt-4 pt-3 sm:pt-4 border-t border-gray-200">
                        <div className="bg-green-50 p-3 sm:p-4 rounded-lg mb-3 sm:mb-4">
                          <p className="text-xs sm:text-sm font-medium text-gray-700 mb-1">
                            Correct Response:
                          </p>
                          <p className="text-sm sm:text-base md:text-lg font-semibold text-green-800 break-words">
                            {item.question.question}
                          </p>
                        </div>
                        <div className="bg-gray-50 p-3 rounded-lg mt-3">
                          <div className="flex flex-col sm:flex-row items-start sm:items-center gap-2 sm:gap-4 text-gray-700 text-xs sm:text-sm">
                            <div className="flex items-center gap-2 flex-wrap">
                              <span className="font-semibold text-jeopardy-blue">Original Category:</span>
                              <span className="font-medium break-words">{item.question.category}</span>
                            </div>
                            {item.question.air_date && (
                              <>
                                <span className="text-gray-400 hidden sm:inline">•</span>
                                <div className="flex items-center gap-2 flex-wrap">
                                  <span className="font-semibold text-jeopardy-blue">Aired:</span>
                                  <span className="font-medium">
                                    {new Date(item.question.air_date).toLocaleDateString("en-US", {
                                      year: "numeric",
                                      month: "long",
                                      day: "numeric"
                                    })}
                                  </span>
                                </div>
                              </>
                            )}
                          </div>
                        </div>
                        <div className="mt-3 sm:mt-4 text-center">
                          <button
                            onClick={(e) => {
                              e.stopPropagation();
                              handleArchive(item.question.id);
                            }}
                            className="px-3 py-1 text-xs text-gray-500 hover:text-gray-700 underline transition-colors"
                          >
                            Archive question (if media missing)
                          </button>
                        </div>
                        </div>
                      )}
                    </div>
                  </div>
                );
              })}
            </div>
          </>
        )}
      </div>
    </div>
  );
}

// frontend/src/routes/review/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { getAuth } from '$lib/auth.svelte';
  import { goto } from '$app/navigation';
  import { api } from '$lib/api';
  import QuestionCard from '$lib/components/QuestionCard.svelte';
  import CategoryFilter from '$lib/components/CategoryFilter.svelte';
  import MasteryBadge from '$lib/components/MasteryBadge.svelte';

  const auth = getAuth();

  $effect(() => {
    if (!auth.loading && !auth.user) goto('/login');
  });

  // --- Types ---
  interface ReviewItem {
    question: {
      id: number;
      question: string;
      answer: string;
      category: string;
      classifier_category: string;
      clue_value: number | null;
      round: number | null;
      air_date: string | null;
    };
    masteryProgress: {
      consecutive_correct: number;
      required: number;
    };
  }

  // --- State ---
  let reviewItems = $state<ReviewItem[]>([]);
  let categories = $state<Array<{ name: string; count: number }>>([]);
  let selectedCategory = $state('all');
  let loading = $state(true);
  let error = $state('');
  let expandedId = $state<number | null>(null);
  let archivingId = $state<number | null>(null);

  // Review session state
  let inSession = $state(false);
  let sessionItems = $state<ReviewItem[]>([]);
  let sessionIndex = $state(0);
  let showAnswer = $state(false);
  let submitting = $state(false);
  let sessionId = $state<number | null>(null);

  // Sorted: closest to mastery first (highest consecutive_correct)
  let sortedItems = $derived(
    [...reviewItems].sort(
      (a, b) => b.masteryProgress.consecutive_correct - a.masteryProgress.consecutive_correct
    )
  );

  let currentSessionItem = $derived(
    sessionItems.length > 0 && sessionIndex < sessionItems.length
      ? sessionItems[sessionIndex]
      : null
  );

  // --- API ---
  async function fetchReviewItems() {
    loading = true;
    error = '';
    try {
      const params = new URLSearchParams();
      if (selectedCategory !== 'all') params.set('category', selectedCategory);
      reviewItems = await api.get(`/api/review?${params}`);
    } catch (err: any) {
      error = err?.message ?? 'Failed to load review items';
    } finally {
      loading = false;
    }
  }

  async function handleArchive(questionId: number) {
    archivingId = questionId;
    try {
      await api.post(`/api/questions/${questionId}/archive`, {
        reason: 'Archived from review',
      });
      reviewItems = reviewItems.filter((item) => item.question.id !== questionId);
      expandedId = null;
    } catch (err: any) {
      error = err?.message ?? 'Failed to archive question';
    } finally {
      archivingId = null;
    }
  }

  async function handleCategoryChange(value: string) {
    selectedCategory = value;
    await fetchReviewItems();
  }

  // --- Review Session ---
  function startSession() {
    sessionItems = [...sortedItems];
    sessionIndex = 0;
    showAnswer = false;
    sessionId = null;
    inSession = true;
  }

  async function handleSessionAnswer(correct: boolean) {
    if (!currentSessionItem || submitting) return;
    submitting = true;
    try {
      const result = await api.post('/api/quiz/submit', {
        questionId: currentSessionItem.question.id,
        correct,
        sessionId,
        isReviewSession: true,
      });
      sessionId = result.sessionId;
      showAnswer = false;

      if (sessionIndex + 1 >= sessionItems.length) {
        // Session complete
        await fetchReviewItems();
        inSession = false;
        sessionItems = [];
        sessionIndex = 0;
        sessionId = null;
      } else {
        sessionIndex++;
      }
    } catch (err: any) {
      error = err?.message ?? 'Failed to submit answer';
    } finally {
      submitting = false;
    }
  }

  async function endSession() {
    await fetchReviewItems();
    inSession = false;
    sessionItems = [];
    sessionIndex = 0;
    showAnswer = false;
    sessionId = null;
  }

  // --- Keyboard shortcuts for session ---
  function handleKeydown(e: KeyboardEvent) {
    if (!inSession) return;
    if (e.target instanceof HTMLInputElement || e.target instanceof HTMLSelectElement) return;

    if (e.code === 'Space' && !showAnswer) {
      e.preventDefault();
      showAnswer = true;
    } else if (e.code === 'ArrowRight' && showAnswer && !submitting) {
      handleSessionAnswer(true);
    } else if (e.code === 'ArrowLeft' && showAnswer && !submitting) {
      handleSessionAnswer(false);
    }
  }

  // --- Mount ---
  onMount(async () => {
    try {
      const cats = await api.get('/api/categories');
      categories = cats ?? [];
    } catch {
      // Non-critical
    }
    await fetchReviewItems();
  });
</script>

<svelte:window onkeydown={handleKeydown} />

<div class="min-h-screen bg-gray-50 py-6 px-4">
  <div class="max-w-2xl mx-auto flex flex-col gap-4">

    {#if inSession}
      <!-- ===== REVIEW SESSION ===== -->
      <div class="flex items-center justify-between">
        <h1 class="text-2xl font-bold text-jeopardy-blue">Review Session</h1>
        <button
          onclick={endSession}
          class="px-4 py-1.5 rounded-lg border border-gray-300 text-sm text-gray-700 hover:bg-gray-100 transition-colors"
        >
          End Session
        </button>
      </div>

      <!-- Progress bar -->
      <div>
        <div class="flex justify-between text-xs text-gray-500 mb-1">
          <span>Question {sessionIndex + 1} of {sessionItems.length}</span>
          <span>{Math.round(((sessionIndex) / sessionItems.length) * 100)}%</span>
        </div>
        <div class="w-full bg-gray-200 rounded-full h-2">
          <div
            class="bg-jeopardy-blue h-2 rounded-full transition-all"
            style="width: {(sessionIndex / sessionItems.length) * 100}%"
          ></div>
        </div>
      </div>

      {#if error}
        <div class="px-4 py-3 bg-red-50 border border-red-200 text-red-700 rounded-lg text-sm">
          {error}
          <button onclick={() => (error = '')} class="ml-2 underline text-red-500">Dismiss</button>
        </div>
      {/if}

      {#if currentSessionItem}
        <div class="min-h-[420px]">
          <QuestionCard
            clue={currentSessionItem.question.answer}
            answer={currentSessionItem.question.question}
            category={currentSessionItem.question.category}
            classifierCategory={currentSessionItem.question.classifier_category}
            clueValue={currentSessionItem.question.clue_value}
            round={currentSessionItem.question.round}
            airDate={currentSessionItem.question.air_date}
            {showAnswer}
            onRevealAnswer={() => { showAnswer = true; }}
            onCorrect={() => handleSessionAnswer(true)}
            onIncorrect={() => handleSessionAnswer(false)}
            {submitting}
          >
            {#snippet badge()}
              <MasteryBadge
                consecutiveCorrect={currentSessionItem.masteryProgress.consecutive_correct}
                required={currentSessionItem.masteryProgress.required}
              />
            {/snippet}
          </QuestionCard>
        </div>

        <p class="text-center text-xs text-gray-400">
          {#if !showAnswer}
            Press <kbd class="px-1.5 py-0.5 bg-gray-100 rounded border border-gray-300 font-mono">Space</kbd> to reveal answer
          {:else}
            <kbd class="px-1.5 py-0.5 bg-gray-100 rounded border border-gray-300 font-mono">←</kbd> Incorrect &nbsp;
            <kbd class="px-1.5 py-0.5 bg-gray-100 rounded border border-gray-300 font-mono">→</kbd> Correct
          {/if}
        </p>
      {/if}

    {:else}
      <!-- ===== LIST VIEW ===== -->
      <div class="flex items-center justify-between">
        <h1 class="text-2xl font-bold text-jeopardy-blue">Review</h1>
        {#if reviewItems.length > 0}
          <button
            onclick={startSession}
            class="px-4 py-2 bg-jeopardy-blue text-white text-sm font-semibold rounded-lg hover:bg-blue-800 transition-colors"
          >
            Start Review Session
          </button>
        {/if}
      </div>

      <!-- Category filter -->
      <div class="bg-white rounded-xl shadow-sm px-5 py-4">
        <p class="block text-xs font-semibold text-gray-500 uppercase tracking-wide mb-1">Category</p>
        <CategoryFilter
          {categories}
          selected={selectedCategory}
          onchange={handleCategoryChange}
        />
      </div>

      {#if error}
        <div class="px-4 py-3 bg-red-50 border border-red-200 text-red-700 rounded-lg text-sm">
          {error}
          <button onclick={() => (error = '')} class="ml-2 underline text-red-500">Dismiss</button>
        </div>
      {/if}

      {#if loading}
        <div class="flex justify-center py-16">
          <div class="animate-spin rounded-full h-12 w-12 border-b-2 border-jeopardy-blue"></div>
        </div>
      {:else if sortedItems.length === 0}
        <div class="text-center py-16 text-gray-500">
          <p class="text-lg font-medium">No questions to review!</p>
          <p class="text-sm mt-1">Answer some questions incorrectly to see them here.</p>
        </div>
      {:else}
        <div class="flex flex-col gap-3">
          {#each sortedItems as item (item.question.id)}
            {@const expanded = expandedId === item.question.id}
            <div class="bg-white rounded-xl shadow-sm overflow-hidden border border-gray-100">
              <!-- Card header (always visible) -->
              <button
                class="w-full text-left px-5 py-4 hover:bg-gray-50 transition-colors"
                onclick={() => { expandedId = expanded ? null : item.question.id; }}
              >
                <div class="flex items-center gap-2 flex-wrap mb-2">
                  <span class="inline-flex items-center px-2 py-0.5 rounded-full text-xs font-semibold bg-blue-100 text-blue-800">
                    {item.question.classifier_category}
                  </span>
                  {#if item.question.clue_value}
                    <span class="text-xs text-gray-500 font-medium">${item.question.clue_value.toLocaleString()}</span>
                  {/if}
                  <MasteryBadge
                    consecutiveCorrect={item.masteryProgress.consecutive_correct}
                    required={item.masteryProgress.required}
                  />
                  <span class="ml-auto text-gray-400 text-xs">{expanded ? '▲' : '▼'}</span>
                </div>
                <p class="text-sm text-gray-700 line-clamp-2">{item.question.answer}</p>
              </button>

              <!-- Expanded content -->
              {#if expanded}
                <div class="px-5 pb-4 border-t border-gray-100 pt-3">
                  <div class="mb-3">
                    <p class="text-xs font-semibold text-gray-500 uppercase tracking-wide mb-1">Correct Response</p>
                    <p class="text-gray-900 font-medium">{item.question.question}</p>
                  </div>
                  <div class="flex flex-wrap gap-4 text-xs text-gray-500 mb-4">
                    <span>
                      <span class="font-semibold">Category:</span> {item.question.category}
                    </span>
                    {#if item.question.air_date}
                      <span>
                        <span class="font-semibold">Air Date:</span> {item.question.air_date}
                      </span>
                    {/if}
                  </div>
                  <button
                    onclick={() => handleArchive(item.question.id)}
                    disabled={archivingId === item.question.id}
                    class="px-3 py-1.5 text-xs rounded-lg border border-gray-300 text-gray-600 hover:bg-gray-50 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
                  >
                    {archivingId === item.question.id ? 'Archiving...' : 'Archive Question'}
                  </button>
                </div>
              {/if}
            </div>
          {/each}
        </div>
      {/if}
    {/if}

  </div>
</div>
