// frontend/src/routes/coryat/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { getAuth } from '$lib/auth.svelte';
  import { goto } from '$app/navigation';
  import { api } from '$lib/api';

  const auth = getAuth();

  $effect(() => {
    if (!auth.loading && !auth.user) goto('/login');
  });

  interface GameRecord {
    id: number;
    completed_at: string | null;
    jeopardy_score: number;
    double_jeopardy_score: number;
    final_score: number | null;
    created_at: string;
  }

  let history = $state<GameRecord[]>([]);
  let loading = $state(true);
  let starting = $state(false);
  let error = $state('');

  let totalGames = $derived(history.filter((g) => g.completed_at !== null).length);
  let avgScore = $derived(
    totalGames > 0
      ? Math.round(
          history.filter((g) => g.completed_at !== null).reduce((sum, g) => sum + (g.final_score ?? 0), 0) /
            totalGames
        )
      : 0
  );
  let bestScore = $derived(
    totalGames > 0
      ? Math.max(...history.filter((g) => g.completed_at !== null).map((g) => g.final_score ?? 0))
      : 0
  );
  let incompleteGame = $derived(history.find((g) => g.completed_at === null) ?? null);

  onMount(async () => {
    try {
      history = await api.get('/api/coryat/history');
    } catch (err: any) {
      error = err?.message ?? 'Failed to load history';
    } finally {
      loading = false;
    }
  });

  async function startGame() {
    starting = true;
    error = '';
    try {
      const result = await api.post('/api/coryat');
      goto(`/coryat/${result.game_id}`);
    } catch (err: any) {
      error = err?.message ?? 'Failed to start game';
      starting = false;
    }
  }
</script>
<svelte:head>
  <title>Coryat — Jeopardy! Training</title>
</svelte:head>


<div class="min-h-screen bg-gray-50 py-8 px-4">
  <div class="max-w-3xl mx-auto flex flex-col gap-6">

    <!-- Header -->
    <div>
      <div class="flex items-center justify-between gap-3">
        <h1 class="text-3xl font-bold text-jeopardy-blue mb-2">Coryat Score Practice</h1>
        <button
          onclick={() => goto('/dashboard')}
          class="shrink-0 px-3 py-1.5 rounded-lg border border-gray-300 text-sm text-gray-700 hover:bg-gray-100 transition-colors"
        >
          Done
        </button>
      </div>
      <p class="text-gray-600">
        The Coryat score is a self-scoring method where you play along with Jeopardy! without wagering.
        Correct answers add the clue value; incorrect answers subtract the clue value. Passes are free.
        This gives you a consistent benchmark independent of luck.
      </p>
    </div>

    <!-- Benchmark Table -->
    <div class="bg-white rounded-xl shadow p-6">
      <h2 class="text-lg font-semibold text-gray-800 mb-4">Score Benchmarks</h2>
      <table class="min-w-full text-sm">
        <thead>
          <tr class="border-b border-gray-200">
            <th class="text-left py-2 px-3 font-semibold text-gray-600">Score Range</th>
            <th class="text-left py-2 px-3 font-semibold text-gray-600">Level</th>
          </tr>
        </thead>
        <tbody>
          <tr class="border-b border-gray-100">
            <td class="py-2 px-3 text-red-600 font-medium">Below $16,000</td>
            <td class="py-2 px-3 text-gray-700">Keep practicing</td>
          </tr>
          <tr class="border-b border-gray-100">
            <td class="py-2 px-3 text-amber-600 font-medium">~$24,000</td>
            <td class="py-2 px-3 text-gray-700">Average contestant</td>
          </tr>
          <tr class="border-b border-gray-100">
            <td class="py-2 px-3 text-blue-600 font-medium">~$28,000</td>
            <td class="py-2 px-3 text-gray-700">Strong player</td>
          </tr>
          <tr>
            <td class="py-2 px-3 text-green-600 font-medium">$32,000+</td>
            <td class="py-2 px-3 text-gray-700">Excellent / champion level</td>
          </tr>
        </tbody>
      </table>
    </div>

    <!-- User Stats -->
    {#if loading}
      <div class="flex justify-center py-8">
        <div class="animate-spin rounded-full h-10 w-10 border-b-2 border-jeopardy-blue"></div>
      </div>
    {:else if totalGames > 0}
      <div class="bg-white rounded-xl shadow p-6">
        <h2 class="text-lg font-semibold text-gray-800 mb-4">Your Stats</h2>
        <div class="flex flex-wrap gap-4">
          <div class="flex-1 min-w-[120px] bg-gray-50 rounded-lg p-4 text-center">
            <p class="text-sm text-gray-500 mb-1">Games Played</p>
            <p class="text-2xl font-bold text-jeopardy-blue">{totalGames}</p>
          </div>
          <div class="flex-1 min-w-[120px] bg-gray-50 rounded-lg p-4 text-center">
            <p class="text-sm text-gray-500 mb-1">Avg Score</p>
            <p class="text-2xl font-bold text-jeopardy-blue">${avgScore.toLocaleString()}</p>
          </div>
          <div class="flex-1 min-w-[120px] bg-gray-50 rounded-lg p-4 text-center">
            <p class="text-sm text-gray-500 mb-1">Best Score</p>
            <p class="text-2xl font-bold text-green-600">${bestScore.toLocaleString()}</p>
          </div>
        </div>
      </div>
    {/if}

    <!-- Error -->
    {#if error}
      <div class="px-4 py-3 bg-red-50 border border-red-200 text-red-700 rounded-lg text-sm">
        {error}
      </div>
    {/if}

    <!-- Actions -->
    <div class="flex flex-wrap gap-3">
      {#if incompleteGame}
        <a
          href="/coryat/{incompleteGame.id}"
          class="px-6 py-3 bg-amber-500 hover:bg-amber-600 text-white font-semibold rounded-lg transition-colors"
        >
          Resume Game
        </a>
      {/if}
      <button
        onclick={startGame}
        disabled={starting}
        class="px-6 py-3 bg-jeopardy-blue hover:bg-blue-800 disabled:opacity-60 text-white font-semibold rounded-lg transition-colors"
      >
        {starting ? 'Starting...' : 'Start New Game'}
      </button>
      <a
        href="/coryat/history"
        class="px-6 py-3 border border-gray-300 hover:bg-gray-100 text-gray-700 font-semibold rounded-lg transition-colors"
      >
        View History
      </a>
    </div>

  </div>
</div>

// app/coryat/page.tsx
"use client";

import { useState, useEffect } from "react";
import { useSession } from "next-auth/react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import Navigation from "../components/Navigation";

interface IncompleteGame {
  id: number;
  started_at: string;
  questions_answered: number;
  jeopardy_score: number;
  double_j_score: number;
}

interface Statistics {
  total_games: number;
  average_score: number;
  best_score: number;
}

export default function CoryatLobbyPage() {
  const { data: session, status } = useSession();
  const router = useRouter();
  const [loading, setLoading] = useState(false);
  const [incompleteGame, setIncompleteGame] = useState<IncompleteGame | null>(null);
  const [statistics, setStatistics] = useState<Statistics | null>(null);

  useEffect(() => {
    if (status === "unauthenticated") {
      router.push("/login");
    }
  }, [status, router]);

  useEffect(() => {
    if (status === "authenticated") {
      fetchHistory();
    }
  }, [status]);

  const fetchHistory = async () => {
    try {
      const response = await fetch("/api/coryat/history");
      const data = await response.json();
      setIncompleteGame(data.incomplete_game);
      setStatistics(data.statistics);
    } catch (error) {
      console.error("Error fetching history:", error);
    }
  };

  const handleStartNewGame = async () => {
    setLoading(true);
    try {
      const response = await fetch("/api/coryat/create", {
        method: "POST",
      });
      const data = await response.json();

      if (data.success) {
        router.push(`/coryat/${data.gameId}`);
      } else {
        alert("Failed to create game");
      }
    } catch (error) {
      console.error("Error creating game:", error);
      alert("Failed to create game");
    } finally {
      setLoading(false);
    }
  };

  if (status === "loading") {
    return (
      <div className="min-h-screen flex items-center justify-center bg-gray-100">
        <div className="text-xl">Loading...</div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-100">
      <Navigation title="Coryat Training Mode" username={session?.user?.username} userRole={session?.user?.role} />

      <div className="max-w-4xl mx-auto p-8">
        {/* Main Card */}
        <div className="bg-white p-8 rounded-lg shadow-lg mb-6">
          <h1 className="text-3xl font-bold text-jeopardy-blue mb-4">
            Coryat Training Mode
          </h1>
          <p className="text-gray-700 mb-6">
            Practice with full Jeopardy! game boards using the Coryat scoring method developed by Karl Coryat.
            Play through 60 questions across Jeopardy! and Double Jeopardy! rounds, plus Final Jeopardy! for practice.
          </p>

          {/* How It Works */}
          <div className="bg-blue-50 p-4 rounded-lg mb-6">
            <h3 className="font-semibold text-gray-800 mb-2">How It Works:</h3>
            <ul className="list-disc list-inside space-y-1 text-gray-700 text-sm">
              <li>Select clues from a 6×5 game board, just like the real show</li>
              <li>Add the dollar value for correct answers, subtract for incorrect</li>
              <li>Pass on questions you don't know (no penalty)</li>
              <li>Daily Doubles shown but scored as regular clues</li>
              <li>Final Jeopardy! for practice only (not counted in score)</li>
              <li>Your Coryat score = Jeopardy! + Double Jeopardy! totals</li>
            </ul>
          </div>

          {/* Statistics */}
          {statistics && statistics.total_games > 0 && (
            <div className="grid grid-cols-3 gap-4 mb-6">
              <div className="bg-gray-50 p-4 rounded-lg text-center">
                <div className="text-2xl font-bold text-jeopardy-blue">
                  {statistics.total_games}
                </div>
                <div className="text-sm text-gray-600">Games Played</div>
              </div>
              <div className="bg-gray-50 p-4 rounded-lg text-center">
                <div className="text-2xl font-bold text-green-600">
                  ${statistics.average_score.toLocaleString()}
                </div>
                <div className="text-sm text-gray-600">Average Score</div>
              </div>
              <div className="bg-gray-50 p-4 rounded-lg text-center">
                <div className="text-2xl font-bold text-jeopardy-gold">
                  ${statistics.best_score.toLocaleString()}
                </div>
                <div className="text-sm text-gray-600">Best Score</div>
              </div>
            </div>
          )}

          {/* Resume Incomplete Game */}
          {incompleteGame && (
            <div className="bg-yellow-50 border-2 border-yellow-300 p-4 rounded-lg mb-6">
              <h3 className="font-semibold text-gray-800 mb-2">Resume Game in Progress</h3>
              <p className="text-gray-700 mb-3">
                Started {new Date(incompleteGame.started_at).toLocaleString()} •
                {incompleteGame.questions_answered} questions answered •
                Current total: ${(incompleteGame.jeopardy_score + incompleteGame.double_j_score).toLocaleString()}
              </p>
              <Link
                href={`/coryat/${incompleteGame.id}`}
                className="inline-block px-6 py-3 bg-yellow-500 text-white font-bold rounded-lg hover:bg-yellow-600 transition-colors"
              >
                Resume Game
              </Link>
            </div>
          )}

          {/* Action Buttons */}
          <div className="flex gap-4">
            <button
              onClick={handleStartNewGame}
              disabled={loading}
              className="flex-1 px-8 py-4 bg-jeopardy-blue text-white font-bold text-xl rounded-lg hover:bg-blue-700 transition-colors disabled:bg-gray-400"
            >
              {loading ? "Creating Game..." : "Start New Game"}
            </button>
            <Link
              href="/coryat/history"
              className="px-8 py-4 bg-gray-600 text-white font-bold text-xl rounded-lg hover:bg-gray-700 transition-colors text-center"
            >
              View History
            </Link>
          </div>
        </div>

        {/* Scoring Reference */}
        <div className="bg-white p-6 rounded-lg shadow-lg">
          <h3 className="font-semibold text-gray-800 mb-3">Coryat Score Benchmarks:</h3>
          <div className="space-y-2 text-sm text-gray-700">
            <div className="flex justify-between">
              <span>Under $16,000:</span>
              <span className="font-medium">Keep practicing</span>
            </div>
            <div className="flex justify-between">
              <span>Around $24,000:</span>
              <span className="font-medium">Average contestant level</span>
            </div>
            <div className="flex justify-between">
              <span>Around $28,000:</span>
              <span className="font-medium">Strong audition candidate</span>
            </div>
            <div className="flex justify-between">
              <span>$32,000+:</span>
              <span className="font-medium">Excellent performance</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
