// app/mastered/page.tsx
"use client";

import { useState, useEffect } from "react";
import { useSession } from "next-auth/react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import Navigation from "../components/Navigation";
import QuestionCard from "../components/QuestionCard";

interface MasteredQuestion {
  id: number;
  question: string;
  answer: string;
  category: string;
  classifier_category: string;
  clue_value: number | null;
  round: number | null;
  air_date: string | null;
  mastered_at: string | null;
  total_mastered: number;
}

export default function MasteredPage() {
  const { data: session, status } = useSession();
  const router = useRouter();
  const [question, setQuestion] = useState<MasteredQuestion | null>(null);
  const [showAnswer, setShowAnswer] = useState(false);
  const [loading, setLoading] = useState(true);
  const [categories, setCategories] = useState<Array<{ name: string; count: number }>>([]);
  const [selectedCategory, setSelectedCategory] = useState("all");

  useEffect(() => {
    if (status === "unauthenticated") {
      router.push("/login");
    }
  }, [status, router]);

  useEffect(() => {
    fetchCategories();
  }, []);

  useEffect(() => {
    if (status === "authenticated") {
      fetchQuestion();
    }
  }, [status, selectedCategory]);

  // Keyboard shortcuts
  useEffect(() => {
    const handleKeyPress = (e: KeyboardEvent) => {
      if (e.target instanceof HTMLInputElement || e.target instanceof HTMLSelectElement) {
        return;
      }

      if (e.key === " " || e.key === "Spacebar") {
        e.preventDefault();
        if (!showAnswer) {
          setShowAnswer(true);
        }
      }
    };

    window.addEventListener("keydown", handleKeyPress);
    return () => window.removeEventListener("keydown", handleKeyPress);
  }, [showAnswer, question]);

  const fetchCategories = async () => {
    try {
      const response = await fetch("/api/categories");
      const data = await response.json();
      setCategories(data);
    } catch (error) {
      console.error("Error fetching categories:", error);
    }
  };

  const fetchQuestion = async () => {
    setLoading(true);
    setShowAnswer(false);

    try {
      const url = selectedCategory === "all"
        ? "/api/mastered"
        : `/api/mastered?category=${encodeURIComponent(selectedCategory)}`;

      const response = await fetch(url);

      if (!response.ok) {
        const error = await response.json();
        if (response.status === 404) {
          setQuestion(null);
        }
        throw new Error(error.error || "Failed to fetch question");
      }

      const data = await response.json();
      setQuestion(data);
    } catch (error) {
      console.error("Error fetching question:", error);
      setQuestion(null);
    } finally {
      setLoading(false);
    }
  };

  const handleAnswer = async (correct: boolean) => {
    if (!question) return;

    try {
      await fetch("/api/quiz/submit", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          questionId: question.id,
          correct,
          sessionId: null, // Don't track sessions for mastered review
          isReviewSession: true,
        }),
      });

      // Fetch next question
      setTimeout(() => {
        fetchQuestion();
      }, 300);
    } catch (error) {
      console.error("Error submitting answer:", error);
    }
  };

  const handleResetMastery = async () => {
    if (!question) return;

    if (!confirm("Are you sure you want to reset mastery for this question? It will be added back to your review queue.")) {
      return;
    }

    try {
      await fetch("/api/mastery/reset", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          questionId: question.id,
        }),
      });

      // Fetch next question
      setTimeout(() => {
        fetchQuestion();
      }, 300);
    } catch (error) {
      console.error("Error resetting mastery:", error);
    }
  };

  if (status === "loading" || loading) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-gray-100">
        <div className="text-xl">Loading...</div>
      </div>
    );
  }

  if (!question) {
    return (
      <div className="min-h-screen bg-gray-100">
        <Navigation title="Mastered Questions Review" username={session?.user?.username} userRole={session?.user?.role} />

        <div className="max-w-4xl mx-auto p-8">
          <div className="bg-white p-12 rounded-lg shadow text-center">
            <h2 className="text-2xl font-bold text-gray-800 mb-4">
              No Mastered Questions Found
            </h2>
            <p className="text-gray-600 mb-6">
              {selectedCategory === "all"
                ? "You haven't mastered any questions yet. Answer questions correctly 3 times in a row to master them!"
                : `You haven't mastered any questions in the ${selectedCategory} category yet.`}
            </p>
            <Link
              href="/quiz"
              className="inline-block px-8 py-3 bg-jeopardy-blue text-white font-bold rounded-lg hover:bg-blue-700 transition-colors"
            >
              Start Quiz
            </Link>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-100">
      <Navigation title="Mastered Questions Review" username={session?.user?.username} bgColor="bg-green-700" />

      {/* Stats & Category Filter */}
      <div className="bg-white shadow-sm p-4">
        <div className="max-w-6xl mx-auto">
          <div className="mb-4 text-center">
            <span className="text-sm font-medium text-gray-700">
              {question.total_mastered} mastered question{question.total_mastered !== 1 ? "s" : ""}
            </span>
          </div>
          <label className="block text-sm font-medium text-gray-700 mb-2">
            Category Filter:
          </label>
          <select
            value={selectedCategory}
            onChange={(e) => setSelectedCategory(e.target.value)}
            className="px-4 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-green-700"
          >
            <option value="all">All Categories</option>
            {categories.map((cat) => (
              <option key={cat.name} value={cat.name}>
                {cat.name} ({cat.count})
              </option>
            ))}
          </select>
        </div>
      </div>

      {/* Question Card */}
      <div className="max-w-4xl mx-auto p-3 sm:p-4 md:p-6 lg:p-8">
        <QuestionCard
          clue={question.answer}
          answer={question.question}
          category={question.category}
          classifierCategory={question.classifier_category}
          clueValue={question.clue_value}
          round={question.round}
          airDate={question.air_date}
          showAnswer={showAnswer}
          onRevealAnswer={() => setShowAnswer(true)}
          onCorrect={() => handleAnswer(true)}
          onIncorrect={() => handleAnswer(false)}
          cardBgColor="bg-green-700"
          cardTextColor="text-yellow-300"
          buttonBgColor="bg-yellow-300"
          buttonTextColor="text-green-800"
          buttonHoverColor="hover:bg-yellow-200"
          keyboardHint={!showAnswer ? "Press Space to reveal" : undefined}
          badge={
            question.mastered_at ? (
              <span className="bg-yellow-300 text-green-800 px-2 sm:px-3 py-1 rounded-full font-semibold text-xs">
                Mastered {new Date(question.mastered_at).toLocaleDateString()}
              </span>
            ) : undefined
          }
          additionalActions={
            showAnswer ? (
              <button
                onClick={handleResetMastery}
                className="flex-1 min-w-[140px] sm:flex-none sm:px-6 md:px-8 py-2 sm:py-3 bg-orange-600 text-white font-bold text-sm sm:text-base md:text-lg rounded-lg hover:bg-orange-700 transition-colors"
              >
                🔄 Reset Mastery
              </button>
            ) : undefined
          }
        />
      </div>
    </div>
  );
}

// frontend/src/routes/mastered/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { getAuth } from '$lib/auth.svelte';
  import { goto } from '$app/navigation';
  import { api } from '$lib/api';
  import QuestionCard from '$lib/components/QuestionCard.svelte';
  import CategoryFilter from '$lib/components/CategoryFilter.svelte';
  import Modal from '$lib/components/Modal.svelte';

  const auth = getAuth();

  $effect(() => {
    if (!auth.loading && !auth.user) goto('/login');
  });

  // --- Types ---
  interface MasteredQuestion {
    id: number;
    question: string;
    answer: string;
    category: string;
    classifier_category: string;
    clue_value: number | null;
    round: number | null;
    air_date: string | null;
    mastered_at: string;
    total_mastered: number;
  }

  // --- State ---
  let masteredQuestion = $state<MasteredQuestion | null>(null);
  let categories = $state<Array<{ name: string; count: number }>>([]);
  let selectedCategory = $state('all');
  let loading = $state(true);
  let error = $state('');
  let showAnswer = $state(false);
  let resetting = $state(false);
  let showResetConfirm = $state(false);

  let masteredDate = $derived(
    masteredQuestion?.mastered_at
      ? new Date(masteredQuestion.mastered_at).toLocaleDateString()
      : ''
  );

  // --- API ---
  async function fetchMastered() {
    loading = true;
    error = '';
    showAnswer = false;
    try {
      const params = new URLSearchParams();
      if (selectedCategory !== 'all') params.set('category', selectedCategory);
      masteredQuestion = await api.get(`/api/mastered?${params}`);
    } catch (err: any) {
      if ((err as any)?.status === 404) {
        masteredQuestion = null;
      } else {
        error = err?.message ?? 'Failed to load mastered question';
      }
    } finally {
      loading = false;
    }
  }

  async function handleResetMastery() {
    if (!masteredQuestion) return;
    resetting = true;
    try {
      await api.post('/api/mastery/reset', { questionId: masteredQuestion.id });
      showResetConfirm = false;
      await fetchMastered();
    } catch (err: any) {
      error = err?.message ?? 'Failed to reset mastery';
    } finally {
      resetting = false;
    }
  }

  async function handleCategoryChange(value: string) {
    selectedCategory = value;
    await fetchMastered();
  }

  // --- Keyboard shortcuts ---
  function handleKeydown(e: KeyboardEvent) {
    if (e.target instanceof HTMLInputElement || e.target instanceof HTMLSelectElement) return;
    if (e.code === 'Space' && !showAnswer && masteredQuestion) {
      e.preventDefault();
      showAnswer = true;
    }
  }

  // --- Mount ---
  onMount(async () => {
    try {
      const cats = await api.get('/api/categories');
      categories = cats ?? [];
    } catch {
      // Non-critical
    }
    await fetchMastered();
  });
</script>
<svelte:head>
  <title>Mastered — Jeopardy! Training</title>
</svelte:head>


<svelte:window onkeydown={handleKeydown} />

<div class="min-h-screen bg-gray-50 py-6 px-4">
  <div class="max-w-2xl mx-auto flex flex-col gap-4">

    <!-- Header -->
    <div class="bg-green-700 rounded-xl px-6 py-4 text-white flex items-start justify-between gap-3">
      <div>
        <h1 class="text-2xl font-bold">Mastered Questions Review</h1>
        {#if masteredQuestion?.total_mastered}
          <p class="text-green-200 text-sm mt-1">{masteredQuestion.total_mastered} mastered question{masteredQuestion.total_mastered === 1 ? '' : 's'}</p>
        {/if}
      </div>
      <button
        onclick={() => goto('/dashboard')}
        class="shrink-0 px-3 py-1.5 rounded-lg border border-white/40 text-sm text-white hover:bg-white/10 transition-colors"
      >
        Done
      </button>
    </div>

    <!-- Category filter -->
    <div class="bg-white rounded-xl shadow-sm px-5 py-4">
      <p class="block text-xs font-semibold text-gray-500 uppercase tracking-wide mb-1">Category</p>
      <CategoryFilter
        {categories}
        selected={selectedCategory}
        onchange={handleCategoryChange}
      />
    </div>

    {#if error}
      <div class="px-4 py-3 bg-red-50 border border-red-200 text-red-700 rounded-lg text-sm">
        {error}
        <button onclick={() => (error = '')} class="ml-2 underline text-red-500">Dismiss</button>
      </div>
    {/if}

    {#if loading}
      <div class="flex justify-center py-16">
        <div class="animate-spin rounded-full h-12 w-12 border-b-2 border-green-700"></div>
      </div>
    {:else if !masteredQuestion}
      <div class="text-center py-16 text-gray-500">
        <p class="text-lg font-medium">No mastered questions yet!</p>
        <p class="text-sm mt-1">Answer questions correctly {3} times in a row to master them.</p>
      </div>
    {:else}
      <div class="min-h-[420px]">
        <QuestionCard
          clue={masteredQuestion.answer}
          answer={masteredQuestion.question}
          category={masteredQuestion.category}
          classifierCategory={masteredQuestion.classifier_category}
          clueValue={masteredQuestion.clue_value}
          round={masteredQuestion.round}
          airDate={masteredQuestion.air_date}
          {showAnswer}
          cardBgColor="bg-green-700"
          cardTextColor="text-yellow-300"
          onRevealAnswer={() => { showAnswer = true; }}
          onCorrect={() => fetchMastered()}
          onIncorrect={() => fetchMastered()}
        >
          {#snippet badge()}
            <span class="inline-flex items-center px-3 py-1 rounded-full text-xs font-semibold bg-green-900 text-green-100">
              Mastered {masteredDate}
            </span>
          {/snippet}

          {#snippet additionalActions()}
            <button
              onclick={() => { showResetConfirm = true; }}
              class="w-full py-2 rounded-lg bg-white/10 hover:bg-white/20 border border-white/20 text-white/80 text-sm font-medium transition-colors"
            >
              Reset Mastery
            </button>
          {/snippet}
        </QuestionCard>
      </div>

      <!-- Next question button -->
      <button
        onclick={() => fetchMastered()}
        class="w-full py-3 rounded-xl bg-green-700 hover:bg-green-800 text-white font-semibold text-lg transition-colors"
      >
        Next Question
      </button>

      <!-- Keyboard hint -->
      <p class="text-center text-xs text-gray-400">
        {#if !showAnswer}
          Press <kbd class="px-1.5 py-0.5 bg-gray-100 rounded border border-gray-300 font-mono">Space</kbd> to reveal answer
        {/if}
      </p>
    {/if}

  </div>
</div>

<!-- Reset mastery confirmation dialog -->
{#if showResetConfirm}
  <Modal onclose={() => (showResetConfirm = false)} ariaLabelledby="reset-mastery-title">
    <div class="rounded-2xl bg-white shadow-2xl p-6 flex flex-col gap-4">
      <h2 id="reset-mastery-title" class="text-lg font-bold text-gray-800">Reset Mastery?</h2>
      <p class="text-sm text-gray-600">
        This will reset the mastery status for this question. You'll need to answer it correctly
        multiple times again to re-master it.
      </p>
      <div class="flex gap-3">
        <button
          onclick={() => { showResetConfirm = false; }}
          class="flex-1 py-2.5 rounded-xl border border-gray-300 text-gray-700 text-sm font-medium hover:bg-gray-50 transition-colors"
        >
          Cancel
        </button>
        <button
          onclick={handleResetMastery}
          disabled={resetting}
          class="flex-1 py-2.5 rounded-xl bg-red-500 text-white text-sm font-semibold hover:bg-red-600 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
        >
          {resetting ? 'Resetting...' : 'Reset Mastery'}
        </button>
      </div>
    </div>
  </Modal>
{/if}
