// app/study/page.tsx
"use client";

import { useState, useEffect } from "react";
import { useSession } from "next-auth/react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import Navigation from "../components/Navigation";

interface StudyTopic {
  topic: string;
  explanation: string;
  readings: string[];
  wikipedia: string[];
  strategies: string[];
}

interface Recommendation {
  id: number;
  generated_at: string;
  days_analyzed: number;
  analysis: string;
  recommendations: StudyTopic[];
  question_count: number;
  time_period_start: string;
  time_period_end: string;
}

interface LatestInfo {
  generated_at: string;
  days_analyzed: number;
  question_count: number;
}

export default function StudyPage() {
  const { data: session, status } = useSession();
  const router = useRouter();
  const [days, setDays] = useState(7);
  const [loading, setLoading] = useState(false);
  const [latestRecommendation, setLatestRecommendation] = useState<Recommendation | null>(null);
  const [latestInfo, setLatestInfo] = useState<LatestInfo | null>(null);
  const [history, setHistory] = useState<Recommendation[]>([]);
  const [expandedHistory, setExpandedHistory] = useState<Set<number>>(new Set());
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (status === "unauthenticated") {
      router.push("/login");
    }
  }, [status, router]);

  useEffect(() => {
    if (status === "authenticated") {
      fetchLatestInfo();
      fetchHistory();
    }
  }, [status]);

  const fetchLatestInfo = async () => {
    try {
      const response = await fetch("/api/study/latest");
      const data = await response.json();
      setLatestInfo(data);
    } catch (error) {
      console.error("Error fetching latest info:", error);
    }
  };

  const fetchHistory = async () => {
    try {
      const response = await fetch("/api/study/history");
      const data = await response.json();

      if (data.length > 0) {
        // Parse recommendations if they're strings (from JSON field)
        const parsedData = data.map((item: any) => ({
          ...item,
          recommendations: typeof item.recommendations === 'string'
            ? JSON.parse(item.recommendations)
            : item.recommendations
        }));

        // Set the most recent as latest recommendation
        setLatestRecommendation(parsedData[0]);
        // Set the rest as history (excluding the first one)
        setHistory(parsedData.slice(1));
      }
    } catch (error) {
      console.error("Error fetching history:", error);
    }
  };

  const handleGenerate = async () => {
    setLoading(true);
    setError(null);

    try {
      const response = await fetch("/api/study/generate", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ days }),
      });

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.error || "Failed to generate recommendations");
      }

      const data = await response.json();

      // Parse recommendations if needed
      const recommendation = {
        ...data.recommendation,
        recommendations: typeof data.recommendation.recommendations === 'string'
          ? JSON.parse(data.recommendation.recommendations)
          : data.recommendation.recommendations
      };

      // Set the new recommendation as latest
      setLatestRecommendation(recommendation);

      // Move the old latest to history if it exists
      if (latestRecommendation) {
        setHistory([latestRecommendation, ...history]);
      }

      // Update latest info
      fetchLatestInfo();
    } catch (error: any) {
      console.error("Error generating recommendations:", error);
      setError(error.message);
    } finally {
      setLoading(false);
    }
  };

  const toggleHistoryExpand = (id: number) => {
    const newExpanded = new Set(expandedHistory);
    if (newExpanded.has(id)) {
      newExpanded.delete(id);
    } else {
      newExpanded.add(id);
    }
    setExpandedHistory(newExpanded);
  };

  if (status === "loading") {
    return (
      <div className="min-h-screen flex items-center justify-center bg-gray-100">
        <div className="text-xl">Loading...</div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-100">
      <Navigation title="Study Recommendations" username={session?.user?.username} />

      <div className="max-w-6xl mx-auto p-8">
        {/* Generation Form */}
        <div className="bg-white p-6 rounded-lg shadow mb-8">
          <h2 className="text-2xl font-bold text-gray-800 mb-4">
            Generate New Recommendations
          </h2>

          <div className="mb-4">
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Analyze last
              <input
                type="number"
                min="1"
                max="365"
                value={days}
                onChange={(e) => setDays(parseInt(e.target.value) || 1)}
                className="mx-2 px-3 py-2 border border-gray-300 rounded-md w-20 text-center focus:outline-none focus:ring-2 focus:ring-jeopardy-blue"
              />
              days
            </label>

            {latestInfo && latestInfo.generated_at ? (
              <p className="text-sm text-gray-500 mt-2">
                Last generated: {new Date(latestInfo.generated_at).toLocaleString()} for {latestInfo.days_analyzed} days ({latestInfo.question_count} questions)
              </p>
            ) : (
              <p className="text-sm text-gray-500 mt-2">
                No recommendations generated yet
              </p>
            )}
          </div>

          <button
            onClick={handleGenerate}
            disabled={loading}
            className="px-6 py-3 bg-jeopardy-blue text-white font-bold rounded-lg hover:bg-blue-700 transition-colors disabled:bg-gray-400 disabled:cursor-not-allowed"
          >
            {loading ? (
              <span className="flex items-center gap-2">
                <svg className="animate-spin h-5 w-5" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                  <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                  <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                </svg>
                Analyzing with AI...
              </span>
            ) : (
              "Generate Study Recommendations"
            )}
          </button>

          {error && (
            <div className="mt-4 p-4 bg-red-100 border border-red-400 text-red-700 rounded">
              {error}
            </div>
          )}
        </div>

        {/* Latest Recommendation */}
        {latestRecommendation && (
          <div className="bg-white p-6 rounded-lg shadow mb-8">
            <div className="mb-6">
              <h2 className="text-2xl font-bold text-gray-800 mb-2">
                Latest Recommendations
              </h2>
              <p className="text-sm text-gray-600">
                Generated {new Date(latestRecommendation.generated_at).toLocaleString()} •
                Analyzed {latestRecommendation.question_count} questions from {new Date(latestRecommendation.time_period_start).toLocaleDateString()} to {new Date(latestRecommendation.time_period_end).toLocaleDateString()}
              </p>
            </div>

            {/* Analysis Summary */}
            <div className="mb-6 p-4 bg-blue-50 rounded-lg">
              <h3 className="text-lg font-semibold text-gray-800 mb-2">
                Pattern Analysis
              </h3>
              <p className="text-gray-700">{latestRecommendation.analysis}</p>
            </div>

            {/* Topics */}
            <div className="space-y-6">
              {Array.isArray(latestRecommendation.recommendations) && latestRecommendation.recommendations.map((topic, index) => (
                <div key={index} className="border border-gray-200 rounded-lg p-6">
                  <h3 className="text-xl font-bold text-jeopardy-blue mb-3">
                    {topic.topic}
                  </h3>

                  <p className="text-gray-700 mb-4">{topic.explanation}</p>

                  {/* Reading Suggestions */}
                  <div className="mb-4">
                    <h4 className="font-semibold text-gray-800 mb-2">📚 Reading Suggestions:</h4>
                    <ul className="list-disc list-inside space-y-1">
                      {topic.readings.map((reading, i) => (
                        <li key={i} className="text-gray-700">{reading}</li>
                      ))}
                    </ul>
                  </div>

                  {/* Wikipedia Resources */}
                  {topic.wikipedia.length > 0 && (
                    <div className="mb-4">
                      <h4 className="font-semibold text-gray-800 mb-2">🔗 Wikipedia Resources:</h4>
                      <ul className="list-disc list-inside space-y-1">
                        {topic.wikipedia.map((link, i) => (
                          <li key={i}>
                            <a
                              href={link}
                              target="_blank"
                              rel="noopener noreferrer"
                              className="text-blue-600 hover:underline"
                            >
                              {link.split('/wiki/')[1]?.replace(/_/g, ' ') || link}
                            </a>
                          </li>
                        ))}
                      </ul>
                    </div>
                  )}

                  {/* Study Strategies */}
                  <div>
                    <h4 className="font-semibold text-gray-800 mb-2">💡 Study Strategies:</h4>
                    <ul className="list-disc list-inside space-y-1">
                      {topic.strategies.map((strategy, i) => (
                        <li key={i} className="text-gray-700">{strategy}</li>
                      ))}
                    </ul>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Historical Recommendations */}
        {history.length > 0 && (
          <div className="bg-white p-6 rounded-lg shadow">
            <h2 className="text-2xl font-bold text-gray-800 mb-4">
              Historical Recommendations
            </h2>
            <p className="text-gray-600 mb-4">
              View past recommendations to track your study progress over time
            </p>

            <div className="space-y-4">
              {history.map((rec) => (
                <div key={rec.id} className="border border-gray-200 rounded-lg">
                  <div
                    className="p-4 cursor-pointer hover:bg-gray-50 transition-colors"
                    onClick={() => toggleHistoryExpand(rec.id)}
                  >
                    <div className="flex justify-between items-center">
                      <div>
                        <p className="font-semibold text-gray-800">
                          {new Date(rec.generated_at).toLocaleDateString()}
                        </p>
                        <p className="text-sm text-gray-600">
                          {rec.days_analyzed} days analyzed • {rec.question_count} questions • {Array.isArray(rec.recommendations) ? rec.recommendations.length : 0} topics
                        </p>
                      </div>
                      <button className="text-gray-400 hover:text-gray-600">
                        {expandedHistory.has(rec.id) ? "−" : "+"}
                      </button>
                    </div>
                  </div>

                  {expandedHistory.has(rec.id) && (
                    <div className="p-4 border-t border-gray-200 bg-gray-50">
                      <p className="text-gray-700 mb-4">{rec.analysis}</p>
                      <div className="space-y-3">
                        {Array.isArray(rec.recommendations) && rec.recommendations.map((topic, index) => (
                          <div key={index} className="text-sm">
                            <p className="font-semibold text-jeopardy-blue">{topic.topic}</p>
                            <p className="text-gray-600 text-xs">{topic.explanation}</p>
                          </div>
                        ))}
                      </div>
                    </div>
                  )}
                </div>
              ))}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

// frontend/src/routes/study/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { getAuth } from '$lib/auth.svelte';
  import { goto } from '$app/navigation';
  import { api } from '$lib/api';

  const auth = getAuth();

  $effect(() => {
    if (!auth.loading && !auth.user) goto('/login');
  });

  interface Topic {
    topic: string;
    explanation: string;
    readings: string[];
    wikipedia: string[];
    strategies: string[];
  }

  interface Recommendation {
    id: number;
    generated_at: string;
    days_analyzed: number;
    analysis: string;
    recommendations: Topic[];
    question_count: number;
  }

  let daysInput = $state(30);
  let generating = $state(false);
  let generateError = $state('');

  let latest = $state<Recommendation | null>(null);
  let latestLoading = $state(true);
  let latestError = $state('');

  let history = $state<Recommendation[]>([]);
  let historyLoading = $state(true);
  let historyError = $state('');
  let expandedHistoryIds = $state<Set<number>>(new Set());

  function toggleHistory(id: number) {
    const next = new Set(expandedHistoryIds);
    if (next.has(id)) {
      next.delete(id);
    } else {
      next.add(id);
    }
    expandedHistoryIds = next;
  }

  function formatDate(dateStr: string): string {
    return new Date(dateStr).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    });
  }

  async function fetchLatest() {
    latestLoading = true;
    latestError = '';
    try {
      latest = await api.get('/api/study/latest');
    } catch (err: any) {
      if (err?.status === 404) {
        latest = null;
      } else {
        latestError = err?.message ?? 'Failed to load latest recommendation';
      }
    } finally {
      latestLoading = false;
    }
  }

  async function fetchHistory() {
    historyLoading = true;
    historyError = '';
    try {
      history = await api.get('/api/study/history');
    } catch (err: any) {
      historyError = err?.message ?? 'Failed to load history';
    } finally {
      historyLoading = false;
    }
  }

  async function handleGenerate() {
    if (generating) return;
    generating = true;
    generateError = '';
    try {
      const result = await api.post('/api/study/generate', { days: daysInput });
      latest = result;
      // Refresh history too
      fetchHistory();
    } catch (err: any) {
      generateError = err?.message ?? 'Failed to generate recommendations';
    } finally {
      generating = false;
    }
  }

  onMount(() => {
    fetchLatest();
    fetchHistory();
  });
</script>
<svelte:head>
  <title>Study — Jeopardy! Training</title>
</svelte:head>


<div class="min-h-screen bg-gray-50 py-8 px-4">
  <div class="max-w-3xl mx-auto flex flex-col gap-8">

    <h1 class="text-3xl font-bold text-jeopardy-blue">Study Recommendations</h1>

    <!-- Generate Form -->
    <div class="bg-white rounded-xl shadow p-6 flex flex-col gap-4">
      <h2 class="text-lg font-semibold text-gray-800">Generate New Recommendations</h2>
      <p class="text-sm text-gray-600">Analyze your recent quiz history and get AI-powered study suggestions.</p>

      <div class="flex flex-col sm:flex-row sm:items-end gap-3">
        <div class="flex flex-col gap-1">
          <label for="days-input" class="text-sm font-medium text-gray-700">Days to analyze</label>
          <input
            id="days-input"
            type="number"
            min="1"
            max="365"
            bind:value={daysInput}
            class="w-32 px-3 py-2 border border-gray-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-jeopardy-blue"
          />
        </div>
        <button
          onclick={handleGenerate}
          disabled={generating}
          class="px-5 py-2 bg-jeopardy-blue hover:bg-blue-800 disabled:opacity-60 text-white font-semibold rounded-lg transition-colors flex items-center gap-2"
        >
          {#if generating}
            <span class="animate-spin rounded-full h-4 w-4 border-b-2 border-white inline-block"></span>
            Analyzing with AI...
          {:else}
            Generate Recommendations
          {/if}
        </button>
      </div>

      {#if generateError}
        <div class="px-3 py-2 bg-red-50 border border-red-200 text-red-700 rounded-lg text-sm">
          {generateError}
        </div>
      {/if}
    </div>

    <!-- Latest Recommendation -->
    <div class="flex flex-col gap-4">
      <h2 class="text-xl font-semibold text-gray-800">Latest Recommendation</h2>

      {#if latestLoading}
        <div class="flex justify-center py-8">
          <div class="animate-spin rounded-full h-8 w-8 border-b-2 border-jeopardy-blue"></div>
        </div>
      {:else if latestError}
        <div class="px-4 py-3 bg-red-50 border border-red-200 text-red-700 rounded-lg text-sm">
          {latestError}
        </div>
      {:else if latest === null}
        <div class="bg-white rounded-xl shadow p-6 text-center text-gray-500">
          No recommendations yet. Generate your first one above!
        </div>
      {:else}
        <div class="text-xs text-gray-500 -mb-2">
          Generated {formatDate(latest.generated_at)} &bull; {latest.days_analyzed} days analyzed &bull; {latest.question_count} questions
        </div>

        <!-- Analysis summary -->
        <div class="bg-indigo-50 border border-indigo-200 rounded-xl p-4">
          <p class="text-indigo-800 text-sm leading-relaxed whitespace-pre-line">{latest.analysis}</p>
        </div>

        <!-- Topic cards -->
        {#each latest.recommendations as topic}
          <div class="bg-white rounded-xl shadow p-5 flex flex-col gap-3">
            <h3 class="text-base font-bold text-gray-800">{topic.topic}</h3>
            <p class="text-sm text-gray-600 leading-relaxed">{topic.explanation}</p>

            {#if topic.readings && topic.readings.length > 0}
              <div>
                <p class="text-xs font-semibold text-gray-500 uppercase tracking-wide mb-1">Readings</p>
                <ul class="flex flex-col gap-1">
                  {#each topic.readings as reading}
                    <li class="text-sm text-gray-700">📚 {reading}</li>
                  {/each}
                </ul>
              </div>
            {/if}

            {#if topic.wikipedia && topic.wikipedia.length > 0}
              <div>
                <p class="text-xs font-semibold text-gray-500 uppercase tracking-wide mb-1">Wikipedia</p>
                <ul class="flex flex-col gap-1">
                  {#each topic.wikipedia as wikiUrl}
                    <li>
                      <a
                        href={wikiUrl}
                        target="_blank"
                        rel="noopener noreferrer"
                        class="text-sm text-blue-600 hover:underline break-all"
                      >
                        {wikiUrl}
                      </a>
                    </li>
                  {/each}
                </ul>
              </div>
            {/if}

            {#if topic.strategies && topic.strategies.length > 0}
              <div>
                <p class="text-xs font-semibold text-gray-500 uppercase tracking-wide mb-1">Strategies</p>
                <ul class="flex flex-col gap-1">
                  {#each topic.strategies as strategy}
                    <li class="text-sm text-gray-700">💡 {strategy}</li>
                  {/each}
                </ul>
              </div>
            {/if}
          </div>
        {/each}
      {/if}
    </div>

    <!-- History Section -->
    <div class="flex flex-col gap-3">
      <h2 class="text-xl font-semibold text-gray-800">History</h2>

      {#if historyLoading}
        <div class="flex justify-center py-6">
          <div class="animate-spin rounded-full h-8 w-8 border-b-2 border-jeopardy-blue"></div>
        </div>
      {:else if historyError}
        <div class="px-4 py-3 bg-red-50 border border-red-200 text-red-700 rounded-lg text-sm">
          {historyError}
        </div>
      {:else if history.length === 0}
        <div class="bg-white rounded-xl shadow p-6 text-center text-gray-500">
          No recommendation history yet.
        </div>
      {:else}
        {#each history as rec}
          <div class="bg-white rounded-xl shadow overflow-hidden">
            <button
              class="w-full flex items-center justify-between px-5 py-4 hover:bg-gray-50 transition-colors text-left"
              onclick={() => toggleHistory(rec.id)}
            >
              <div>
                <p class="font-semibold text-gray-800 text-sm">{formatDate(rec.generated_at)}</p>
                <p class="text-xs text-gray-500 mt-0.5">
                  {rec.days_analyzed} days &bull; {rec.question_count} questions &bull; {rec.recommendations.length} topics
                </p>
              </div>
              <span class="text-gray-400 text-lg">{expandedHistoryIds.has(rec.id) ? '▲' : '▼'}</span>
            </button>

            {#if expandedHistoryIds.has(rec.id)}
              <div class="border-t border-gray-100 px-5 py-4 flex flex-col gap-3">
                <p class="text-sm text-gray-600 leading-relaxed italic">{rec.analysis}</p>
                <ul class="flex flex-col gap-1">
                  {#each rec.recommendations as topic}
                    <li class="text-sm text-gray-700 font-medium">&bull; {topic.topic}</li>
                  {/each}
                </ul>
              </div>
            {/if}
          </div>
        {/each}
      {/if}
    </div>

  </div>
</div>
