// frontend/src/routes/dashboard/+page.svelte
<script lang="ts">
  import { getAuth } from '$lib/auth.svelte';
  import { goto } from '$app/navigation';
  import { api } from '$lib/api';
  import StatsChart from '$lib/components/StatsChart.svelte';
  import { onMount } from 'svelte';

  interface Stats {
    overall: { total: number; correct: number; accuracy: number };
    categoryBreakdown: Array<{ category: string; total: number; correct: number; accuracy: number }>;
    recentSessions: Array<{ id: number; started_at: string; completed_at: string; total: number; correct: number }>;
    dailyStats: Array<{ date: string; avgPercentage: number; sessionCount: number }>;
    dailyAccuracy: Array<{ date: string; total: number; correct: number; accuracy: number }>;
  }

  const auth = getAuth();

  $effect(() => {
    if (!auth.loading && !auth.user) goto('/login');
  });

  let stats = $state<Stats | null>(null);
  let loading = $state(true);
  let error = $state('');
  let includeReviewed = $state(false);

  let srs = $state<{
    dueCount: number;
    newRemaining: number;
    reviewedToday: number;
    forecast: Array<{ date: string; count: number }>;
    adaptiveWeights?: Array<{ category: string; attempts: number; accuracy: number; weight: number }>;
    deck?: { learning: number; mastered: number; struggling: number };
  } | null>(null);

  let lastStudy = $state<string | null>(null);

  async function fetchStats() {
    loading = true;
    error = '';
    try {
      stats = await api.get(`/api/stats?includeReviewed=${includeReviewed}`);
    } catch (err: any) {
      error = err?.message ?? 'Failed to load stats';
    } finally {
      loading = false;
    }
  }

  onMount(() => {
    fetchStats();
    api.get('/api/practice/status').then((s) => (srs = s)).catch(() => (srs = null));
    api
      .get('/api/study/latest')
      .then((s) => (lastStudy = s?.generated_at ?? s?.generatedAt ?? null))
      .catch(() => (lastStudy = null));
  });

  // Re-fetch when toggle changes (but not on initial mount)
  let initialized = false;
  $effect(() => {
    // Access includeReviewed to track the dependency
    const _toggle = includeReviewed;
    if (!initialized) {
      initialized = true;
      return;
    }
    fetchStats();
  });

  // Daily accuracy (last 30 days), computed from every attempt — unlike the old
  // dailyStats series it doesn't depend on sessions being formally completed.
  let lineChartData = $derived(
    stats?.dailyAccuracy?.length
      ? {
          labels: stats.dailyAccuracy.map((d) => d.date),
          datasets: [
            {
              label: 'Accuracy %',
              data: stats.dailyAccuracy.map((d) => d.accuracy),
              borderColor: '#0c47b7',
              borderWidth: 2,
              pointRadius: 3,
              pointHitRadius: 12,
              pointBackgroundColor: '#0c47b7',
              fill: false,
              tension: 0.3,
            },
          ],
        }
      : null
  );

  let lineChartOptions = {
    responsive: true,
    maintainAspectRatio: false,
    plugins: { legend: { display: false } },
    scales: {
      y: {
        min: 0,
        max: 100,
        title: { display: true, text: 'Accuracy %' },
      },
      x: { ticks: { maxRotation: 45 } },
    },
  };

  // 14-day due forecast, padded so quiet days render as true zeros.
  let forecastChartData = $derived.by(() => {
    if (!srs || !srs.forecast) return null;
    const counts = new Map(srs.forecast.map((f) => [f.date, f.count]));
    const start = new Date();
    const labels: string[] = [];
    const data: number[] = [];
    for (let i = 0; i < 14; i++) {
      const d = new Date(Date.UTC(start.getUTCFullYear(), start.getUTCMonth(), start.getUTCDate() + i));
      const key = d.toISOString().slice(0, 10);
      labels.push(i === 0 ? 'Today' : d.toLocaleDateString([], { weekday: 'short', day: 'numeric', timeZone: 'UTC' }));
      data.push(counts.get(key) ?? 0);
    }
    return {
      labels,
      datasets: [
        {
          label: 'Reviews due',
          data,
          backgroundColor: '#0c47b7',
          borderRadius: 4,
          maxBarThickness: 28,
        },
      ],
    };
  });

  let forecastChartOptions = {
    responsive: true,
    maintainAspectRatio: false,
    plugins: { legend: { display: false } },
    scales: {
      y: { min: 0, ticks: { precision: 0 } },
      x: { grid: { display: false } },
    },
  };

  let barChartData = $derived(
    stats
      ? {
          labels: stats.categoryBreakdown.map((c) => c.category),
          datasets: [
            {
              label: 'Accuracy %',
              data: stats.categoryBreakdown.map((c) => c.accuracy),
              backgroundColor: stats.categoryBreakdown.map((c) =>
                c.accuracy >= 75 ? '#22c55e' : c.accuracy >= 50 ? '#f59e0b' : '#ef4444'
              ),
              borderWidth: 1,
            },
          ],
        }
      : null
  );

  let barChartOptions = {
    responsive: true,
    maintainAspectRatio: false,
    scales: {
      y: {
        min: 0,
        max: 100,
        title: { display: true, text: 'Accuracy %' },
      },
      x: { ticks: { maxRotation: 45 } },
    },
  };

  // Category breakdown sorted by accuracy ASC
  let sortedCategories = $derived(
    stats
      ? [...stats.categoryBreakdown].sort((a, b) => a.accuracy - b.accuracy)
      : []
  );
</script>
<svelte:head>
  <title>Dashboard — Jeopardy! Training</title>
</svelte:head>


<div class="min-h-screen bg-gray-50 py-8 px-4">
  <div class="max-w-6xl mx-auto">
    <div class="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 mb-8">
      <h1 class="text-3xl font-bold text-jeopardy-blue">Dashboard</h1>

      <!-- Toggle -->
      <label class="flex items-center gap-2 text-sm font-medium text-gray-700 cursor-pointer">
        <input
          type="checkbox"
          bind:checked={includeReviewed}
          class="w-4 h-4 rounded border-gray-300 text-jeopardy-blue focus:ring-jeopardy-blue"
        />
        Include Review Sessions
      </label>
    </div>

    <!-- SRS Practice Summary -->
    {#if srs}
      <div class="bg-white rounded-xl shadow-sm p-5 mb-8">
        <div class="flex flex-wrap gap-8">
          <div>
            <p class="text-3xl font-bold text-jeopardy-blue">{srs.dueCount}</p>
            <p class="text-xs uppercase text-gray-500">Due today</p>
          </div>
          <div>
            <p class="text-3xl font-bold text-jeopardy-blue">{srs.newRemaining}</p>
            <p class="text-xs uppercase text-gray-500">New left</p>
          </div>
          <div>
            <p class="text-3xl font-bold text-jeopardy-blue">{srs.reviewedToday}</p>
            <p class="text-xs uppercase text-gray-500">Reviewed today</p>
          </div>
          <a
            href="/practice"
            class="ml-auto self-center px-4 py-2 rounded-lg bg-jeopardy-blue text-white text-sm font-semibold hover:bg-blue-800 transition-colors"
          >
            Practice &rarr;
          </a>
        </div>
        {#if forecastChartData}
          <div class="mt-5 pt-4 border-t border-gray-100">
            <h2 class="text-sm font-semibold text-gray-600 mb-2">Reviews due — next 14 days</h2>
            <div class="h-36">
              <StatsChart type="bar" data={forecastChartData} options={forecastChartOptions} />
            </div>
          </div>
        {/if}
        {#if srs.adaptiveWeights && srs.adaptiveWeights.length > 0}
          <div class="mt-5 pt-4 border-t border-gray-100">
            <h2 class="text-sm font-semibold text-gray-600 mb-1">Focus areas</h2>
            <p class="text-xs text-gray-400 mb-3">New clues favor your weaker categories.</p>
            <div class="flex flex-col gap-1.5">
              {#each srs.adaptiveWeights as w, i (w.category)}
                <div class="flex items-center gap-3 text-sm">
                  <span class="w-52 shrink-0 truncate text-gray-700">
                    {w.category}
                    {#if i < 3}
                      <span class="ml-1 px-1.5 py-0.5 rounded-full bg-jeopardy-gold/20 text-jeopardy-blue text-[10px] font-bold uppercase tracking-wide">Targeted</span>
                    {/if}
                  </span>
                  <div class="flex-1 h-2 bg-gray-100 rounded-full overflow-hidden">
                    <div class="h-full bg-jeopardy-blue rounded-full" style="width: {Math.round(w.weight * 100)}%"></div>
                  </div>
                  <span class="w-28 shrink-0 text-right text-xs text-gray-500">
                    {Math.round(w.accuracy)}% · {w.attempts} tries
                  </span>
                </div>
              {/each}
            </div>
          </div>
        {/if}
        {#if srs.deck}
          <div class="mt-5 pt-4 border-t border-gray-100 flex flex-wrap gap-x-5 gap-y-1 text-sm">
            <a href="/cards?state=learning" class="text-jeopardy-blue hover:underline">
              <span class="font-bold">{srs.deck.learning}</span> learning
            </a>
            <a href="/cards?state=mastered" class="text-jeopardy-blue hover:underline">
              <span class="font-bold">{srs.deck.mastered}</span> mastered
            </a>
            <a href="/cards?state=struggling" class="{srs.deck.struggling > 0 ? 'text-red-600' : 'text-jeopardy-blue'} hover:underline">
              <span class="font-bold">{srs.deck.struggling}</span> struggling
            </a>
          </div>
        {/if}
      </div>
    {/if}

    <!-- Study sheets -->
    <a
      href="/study"
      class="bg-white rounded-xl shadow-sm p-5 mb-8 flex items-center justify-between hover:bg-gray-50 transition-colors group block"
    >
      <div>
        <p class="font-semibold text-gray-800">Study sheets</p>
        <p class="text-sm text-gray-500 mt-0.5">
          Generate targeted reading from your recent misses{#if lastStudy}
            — last generated {new Date(lastStudy).toLocaleDateString()}{/if}
        </p>
      </div>
      <span class="text-gray-400 group-hover:text-gray-600 text-lg">&rarr;</span>
    </a>

    <!-- Action Buttons -->
    <div class="flex flex-wrap gap-3 mb-8">
      <a
        href="/practice"
        class="px-5 py-2.5 bg-jeopardy-blue text-white font-semibold rounded-lg hover:bg-blue-800 transition-colors"
      >
        Practice
      </a>
      <a
        href="/drill"
        class="px-5 py-2.5 bg-jeopardy-blue text-white font-semibold rounded-lg hover:bg-blue-800 transition-colors"
      >
        Drill
      </a>
      <a
        href="/coryat"
        class="px-5 py-2.5 bg-jeopardy-blue text-white font-semibold rounded-lg hover:bg-blue-800 transition-colors"
      >
        Coryat
      </a>
    </div>

    {#if loading}
      <div class="flex justify-center py-16">
        <div class="animate-spin rounded-full h-12 w-12 border-b-2 border-jeopardy-blue"></div>
      </div>
    {:else if error}
      <div class="px-4 py-3 bg-red-50 border border-red-200 text-red-700 rounded-lg">
        {error}
      </div>
    {:else if stats}
      <!-- Overall Stats Cards -->
      <div class="flex flex-wrap gap-4 mb-8">
        <div class="flex-1 min-w-[200px] bg-white rounded-xl shadow p-6">
          <p class="text-sm font-medium text-gray-500 mb-1">Total Questions</p>
          <p class="text-3xl font-bold text-jeopardy-blue">{stats.overall.total.toLocaleString()}</p>
        </div>
        <div class="flex-1 min-w-[200px] bg-white rounded-xl shadow p-6">
          <p class="text-sm font-medium text-gray-500 mb-1">Correct Answers</p>
          <p class="text-3xl font-bold text-green-600">{stats.overall.correct.toLocaleString()}</p>
        </div>
        <div class="flex-1 min-w-[200px] bg-white rounded-xl shadow p-6">
          <p class="text-sm font-medium text-gray-500 mb-1">Overall Accuracy</p>
          <p class="text-3xl font-bold {stats.overall.accuracy >= 75 ? 'text-green-600' : stats.overall.accuracy >= 50 ? 'text-amber-500' : 'text-red-500'}">
            {stats.overall.accuracy.toFixed(1)}%
          </p>
        </div>
      </div>

      <!-- Daily Accuracy Chart -->
      {#if lineChartData}
        <div class="bg-white rounded-xl shadow p-6 mb-8">
          <h2 class="text-lg font-semibold text-gray-800 mb-4">Accuracy — last 30 days</h2>
          <div style="height: 300px;">
            <StatsChart type="line" data={lineChartData} options={lineChartOptions} />
          </div>
        </div>
      {:else}
        <div class="bg-white rounded-xl shadow p-6 mb-8 text-center text-gray-400">
          No daily performance data yet.
        </div>
      {/if}

      <!-- Category Performance Chart -->
      {#if stats.categoryBreakdown.length > 0 && barChartData}
        <div class="bg-white rounded-xl shadow p-6 mb-8">
          <h2 class="text-lg font-semibold text-gray-800 mb-4">Category Performance</h2>
          <div style="height: 300px;">
            <StatsChart type="bar" data={barChartData} options={barChartOptions} />
          </div>
        </div>
      {:else}
        <div class="bg-white rounded-xl shadow p-6 mb-8 text-center text-gray-400">
          No category data yet.
        </div>
      {/if}

      <!-- Category Detail Table -->
      {#if sortedCategories.length > 0}
        <div class="bg-white rounded-xl shadow p-6">
          <h2 class="text-lg font-semibold text-gray-800 mb-4">Category Breakdown</h2>
          <div class="overflow-x-auto">
            <table class="min-w-full text-sm">
              <thead>
                <tr class="border-b border-gray-200">
                  <th class="text-left py-3 px-4 font-semibold text-gray-600">Category</th>
                  <th class="text-right py-3 px-4 font-semibold text-gray-600">Total</th>
                  <th class="text-right py-3 px-4 font-semibold text-gray-600">Correct</th>
                  <th class="text-right py-3 px-4 font-semibold text-gray-600">Accuracy</th>
                </tr>
              </thead>
              <tbody>
                {#each sortedCategories as cat}
                  <tr class="border-b border-gray-100 hover:bg-gray-50 transition-colors">
                    <td class="py-3 px-4 text-gray-800">{cat.category}</td>
                    <td class="py-3 px-4 text-right text-gray-600">{cat.total}</td>
                    <td class="py-3 px-4 text-right text-gray-600">{cat.correct}</td>
                    <td class="py-3 px-4 text-right font-medium {cat.accuracy >= 75 ? 'text-green-600' : cat.accuracy >= 50 ? 'text-amber-500' : 'text-red-500'}">
                      {cat.accuracy.toFixed(1)}%
                    </td>
                  </tr>
                {/each}
              </tbody>
            </table>
          </div>
        </div>
      {/if}
    {/if}
  </div>
</div>

// app/dashboard/page.tsx
"use client";

import { useState, useEffect } from "react";
import { useSession } from "next-auth/react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import Navigation from "../components/Navigation";
import {
  BarChart,
  Bar,
  LineChart,
  Line,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  Legend,
  ResponsiveContainer,
  Cell,
} from "recharts";

interface CategoryStat {
  category: string;
  total: number;
  correct: number;
  accuracy: number;
}

interface DailyStat {
  date: string;
  avgPercentage: number;
  sessionCount: number;
}

interface Stats {
  overall: {
    total: number;
    correct: number;
    accuracy: number;
  };
  categoryBreakdown: CategoryStat[];
  recentSessions: Array<{
    id: number;
    started_at: string;
    completed_at: string | null;
    total: number;
    correct: number;
  }>;
  dailyStats: DailyStat[];
}

export default function DashboardPage() {
  const { data: session, status } = useSession();
  const router = useRouter();
  const [stats, setStats] = useState<Stats | null>(null);
  const [loading, setLoading] = useState(true);
  const [includeReviewed, setIncludeReviewed] = useState(false);

  useEffect(() => {
    if (status === "unauthenticated") {
      router.push("/login");
    }
  }, [status, router]);

  useEffect(() => {
    if (status === "authenticated") {
      fetchStats();
    }
  }, [status, includeReviewed]);

  const fetchStats = async () => {
    try {
      const url = `/api/stats?includeReviewed=${includeReviewed}`;
      const response = await fetch(url);
      const data = await response.json();
      setStats(data);
    } catch (error) {
      console.error("Error fetching stats:", error);
    } finally {
      setLoading(false);
    }
  };

  if (status === "loading" || loading) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-gray-100">
        <div className="text-xl">Loading...</div>
      </div>
    );
  }

  if (!stats) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-gray-100">
        <div className="text-xl">No data available</div>
      </div>
    );
  }

  // Get color based on accuracy/proficiency level
  const getAccuracyColor = (accuracy: number) => {
    if (accuracy >= 75) return "#10b981"; // green - Strong
    if (accuracy >= 50) return "#f59e0b"; // yellow/amber - Moderate
    return "#ef4444"; // red - Needs Work
  };

  // Add color to chart data
  const chartData = stats.categoryBreakdown.map(cat => ({
    ...cat,
    fill: getAccuracyColor(cat.accuracy)
  }));

  // Custom legend content for proficiency levels
  const renderLegend = () => (
    <div className="flex justify-center gap-6 mb-4">
      <div className="flex items-center gap-2">
        <div className="w-4 h-4 rounded" style={{ backgroundColor: "#10b981" }}></div>
        <span className="text-sm text-gray-600">Strong (≥75%)</span>
      </div>
      <div className="flex items-center gap-2">
        <div className="w-4 h-4 rounded" style={{ backgroundColor: "#f59e0b" }}></div>
        <span className="text-sm text-gray-600">Moderate (50-74%)</span>
      </div>
      <div className="flex items-center gap-2">
        <div className="w-4 h-4 rounded" style={{ backgroundColor: "#ef4444" }}></div>
        <span className="text-sm text-gray-600">Needs Work (&lt;50%)</span>
      </div>
    </div>
  );

  return (
    <div className="min-h-screen bg-gray-100">
      <Navigation title="Performance Dashboard" username={session?.user?.username} userRole={session?.user?.role} />

      <div className="max-w-6xl mx-auto p-8">
        {/* Filter Toggle */}
        <div className="bg-white p-4 rounded-lg shadow mb-6">
          <div className="flex items-center justify-between">
            <div>
              <h3 className="text-sm font-medium text-gray-700 mb-1">Statistics Filter</h3>
              <p className="text-xs text-gray-500">
                {includeReviewed
                  ? "Showing all questions (including reviewed material)"
                  : "Showing only newly answered questions (review sessions excluded)"}
              </p>
            </div>
            <label className="flex items-center cursor-pointer">
              <div className="relative">
                <input
                  type="checkbox"
                  className="sr-only"
                  checked={includeReviewed}
                  onChange={(e) => setIncludeReviewed(e.target.checked)}
                />
                <div className={`block w-14 h-8 rounded-full transition-colors ${
                  includeReviewed ? 'bg-jeopardy-blue' : 'bg-gray-300'
                }`}></div>
                <div className={`dot absolute left-1 top-1 bg-white w-6 h-6 rounded-full transition-transform ${
                  includeReviewed ? 'transform translate-x-6' : ''
                }`}></div>
              </div>
              <div className="ml-3 text-sm font-medium text-gray-700">
                Include Review Sessions
              </div>
            </label>
          </div>
        </div>

        {/* Overall Stats */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
          <div className="bg-white p-6 rounded-lg shadow">
            <h3 className="text-gray-600 text-sm font-medium mb-2">Total Questions</h3>
            <p className="text-3xl font-bold text-jeopardy-blue">{stats.overall.total}</p>
          </div>
          <div className="bg-white p-6 rounded-lg shadow">
            <h3 className="text-gray-600 text-sm font-medium mb-2">Correct Answers</h3>
            <p className="text-3xl font-bold text-green-600">{stats.overall.correct}</p>
          </div>
          <div className="bg-white p-6 rounded-lg shadow">
            <h3 className="text-gray-600 text-sm font-medium mb-2">Overall Accuracy</h3>
            <p className="text-3xl font-bold text-jeopardy-blue">{stats.overall.accuracy}%</p>
          </div>
        </div>

        {/* Daily Session Performance */}
        {stats.dailyStats && stats.dailyStats.length > 0 && (
          <div className="bg-white p-6 rounded-lg shadow mb-8">
            <h2 className="text-xl font-bold text-gray-800 mb-4">
              Daily Session Performance
            </h2>
            <p className="text-sm text-gray-600 mb-4">
              Average percentage correct per day
            </p>
            <ResponsiveContainer width="100%" height={300}>
              <LineChart data={stats.dailyStats}>
                <CartesianGrid strokeDasharray="3 3" />
                <XAxis
                  dataKey="date"
                  angle={-45}
                  textAnchor="end"
                  height={80}
                  style={{ fontSize: "12px" }}
                />
                <YAxis
                  domain={[0, 100]}
                  label={{ value: 'Average % Correct', angle: -90, position: 'insideLeft' }}
                />
                <Tooltip
                  formatter={(value: number, name: string) => {
                    if (name === 'avgPercentage') {
                      return [`${value.toFixed(1)}%`, 'Avg % Correct'];
                    }
                    return [value, name];
                  }}
                  labelFormatter={(label: string) => `Date: ${label}`}
                />
                <Line
                  type="monotone"
                  dataKey="avgPercentage"
                  stroke="#0c47b7"
                  strokeWidth={2}
                  dot={{ fill: '#0c47b7', r: 4 }}
                  activeDot={{ r: 6 }}
                  name="Avg % Correct"
                />
              </LineChart>
            </ResponsiveContainer>
          </div>
        )}

        {/* Category Performance */}
        {stats.categoryBreakdown.length > 0 && (
          <div className="bg-white p-6 rounded-lg shadow mb-8">
            <h2 className="text-xl font-bold text-gray-800 mb-4">
              Performance by Category
            </h2>
            {renderLegend()}
            <ResponsiveContainer width="100%" height={400}>
              <BarChart data={chartData}>
                <CartesianGrid strokeDasharray="3 3" />
                <XAxis
                  dataKey="category"
                  angle={-45}
                  textAnchor="end"
                  height={150}
                  interval={0}
                  style={{ fontSize: "12px" }}
                />
                <YAxis domain={[0, 100]} label={{ value: 'Accuracy %', angle: -90, position: 'insideLeft' }} />
                <Tooltip />
                <Bar dataKey="accuracy" name="Accuracy %">
                  {chartData.map((entry, index) => (
                    <Cell key={`cell-${entry.category}`} fill={entry.fill} />
                  ))}
                </Bar>
              </BarChart>
            </ResponsiveContainer>
          </div>
        )}

        {/* Category Breakdown Table */}
        {stats.categoryBreakdown.length > 0 && (
          <div className="bg-white p-6 rounded-lg shadow mb-8">
            <h2 className="text-xl font-bold text-gray-800 mb-4">
              Category Details
            </h2>
            <div className="overflow-x-auto">
              <table className="min-w-full divide-y divide-gray-200">
                <thead className="bg-gray-50">
                  <tr>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      Category
                    </th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      Total
                    </th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      Correct
                    </th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      Accuracy
                    </th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      Status
                    </th>
                  </tr>
                </thead>
                <tbody className="bg-white divide-y divide-gray-200">
                  {stats.categoryBreakdown
                    .sort((a, b) => a.accuracy - b.accuracy)
                    .map((cat) => (
                      <tr key={cat.category}>
                        <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                          {cat.category}
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                          {cat.total}
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                          {cat.correct}
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                          {cat.accuracy}%
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap text-sm">
                          {cat.accuracy >= 75 ? (
                            <span className="px-2 py-1 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800">
                              Strong
                            </span>
                          ) : cat.accuracy >= 50 ? (
                            <span className="px-2 py-1 inline-flex text-xs leading-5 font-semibold rounded-full bg-yellow-100 text-yellow-800">
                              Moderate
                            </span>
                          ) : (
                            <span className="px-2 py-1 inline-flex text-xs leading-5 font-semibold rounded-full bg-red-100 text-red-800">
                              Needs Work
                            </span>
                          )}
                        </td>
                      </tr>
                    ))}
                </tbody>
              </table>
            </div>
          </div>
        )}

        {/* Coryat Training */}
        <div className="bg-white p-6 rounded-lg shadow mb-8">
          <h2 className="text-xl font-bold text-gray-800 mb-4">
            Coryat Training Mode
          </h2>
          <p className="text-gray-600 mb-4">
            Practice with full Jeopardy! game boards using the Coryat scoring method.
            Track your progress and aim for the average contestant score of $24,000.
          </p>
          <Link
            href="/coryat"
            className="inline-block px-6 py-3 bg-jeopardy-gold text-jeopardy-blue font-bold rounded-lg hover:bg-yellow-400 transition-colors"
          >
            Start Coryat Game
          </Link>
        </div>

        {/* Action Buttons */}
        <div className="flex flex-col sm:flex-row sm:justify-center gap-4 items-stretch sm:items-center">
          <Link
            href="/quiz"
            className="px-8 py-4 bg-jeopardy-blue text-white font-bold text-xl rounded-lg hover:bg-blue-700 transition-colors text-center min-h-[60px] flex items-center justify-center"
          >
            Start Quiz
          </Link>
          {stats.overall.total > 0 && (
            <>
              <Link
                href="/review"
                className="px-8 py-4 bg-gray-600 text-white font-bold text-xl rounded-lg hover:bg-gray-700 transition-colors text-center min-h-[60px] flex items-center justify-center"
              >
                Review Wrong Answers
              </Link>
              <Link
                href="/mastered"
                className="px-8 py-4 bg-green-700 text-white font-bold text-xl rounded-lg hover:bg-green-800 transition-colors text-center min-h-[60px] flex items-center justify-center"
              >
                Review Mastered Questions
              </Link>
            </>
          )}
        </div>
      </div>
    </div>
  );
}
